# -*- coding: utf-8 -*-
"""Single source of truth for the supplement evidence map.

Convention: never use a raw double-quote character inside a string literal.
Use the typographic marks U+201C / U+201D directly where a quotation is needed.
"""

# verdict codes
TAKE = 'TAKE'          # worth taking if you are in the named group
CONSIDER = 'CONSIDER'  # narrow and conditional; only in a specific situation
SKIP = 'SKIP'          # no good evidence of benefit; a waste of money, not dangerous
AVOID = 'AVOID'        # published evidence of harm

VERDICT_META = {
    TAKE: ('Take it', '值得吃', 'good',
           'Worth taking if you are in the group named under Who. Evidence is strong for that group and for that purpose only.',
           '如果你属于“适用人群”一栏所写的群体，值得吃。证据只对那个群体、那个用途成立。'),
    CONSIDER: ('Consider', '可以考虑', 'warn',
               'Defensible in one narrow situation. Outside that situation there is no case for it.',
               '只在一种很窄的情形下站得住。离开那个情形，就没有理由吃。'),
    SKIP: ('Skip it', '不必买', 'mute',
           'No good evidence of benefit for the marketed claim. Money wasted rather than harm done, unless a Cons entry says otherwise.',
           '对其宣传的功效没有像样的证据。除非“缺点”一栏另有说明，否则问题是浪费钱，不是危害健康。'),
    AVOID: ('Avoid', '不要吃', 'bad',
            'Published evidence of harm in randomised trials, prospective registries or national surveillance.',
            '在随机试验、前瞻性登记或全国性监测中已有公开的致害证据。'),
}

GRADE_META = [
    ('A', 'Consistent meta-analyses of randomised trials with clinical endpoints.',
          '多项随机试验的一致性 meta 分析，且使用临床终点。'),
    ('B', 'Meta-analyses with surrogate endpoints, or good trials with mixed results.',
          '使用替代终点的 meta 分析，或结果不一致的高质量试验。'),
    ('C', 'Small or short randomised trials only.',
          '仅有小样本或短周期的随机试验。'),
    ('D', 'Mechanistic, animal or observational evidence only, or the claim has been refuted.',
          '只有机制、动物或观察性证据，或该主张已被推翻。'),
]

MISREADINGS = [
    ('A high grade does not mean it works. It means we are confident about the answer, and the answer can be no. '
     'Selenium is Grade A in this document because Cochrane established with HIGH certainty that it does NOT prevent cancer. '
     'Read the Grade column together with the Verdict column, never on its own.',
     '高分级不等于有效。它的意思是“我们对结论有把握”，而结论完全可以是“无效”。'
     '本文给硒评 A 级，是因为 Cochrane 以高确定性证明它并不能预防癌症。'
     '“证据分级”这一栏必须和“结论”一栏合起来读，绝不能单看。'),

    ('A grade attaches to one specific claim, not to the substance in general. Vitamin D3 is Grade A for correcting '
     'documented deficiency and Grade D for preventing cancer or cardiovascular disease. Those are the same molecule '
     'and two different questions.',
     '分级针对的是某一个具体主张，而不是这种物质本身。维生素 D3 在“纠正已证实的缺乏”上是 A 级，'
     '在“预防癌症或心血管病”上是 D 级。同一个分子，两个完全不同的问题。'),

    ('An official statement of insufficient evidence is not an endorsement. The USPSTF gives multivitamins an '
     'I statement. That means the trials could neither prove benefit nor rule out harm. The industry quotes it as vindication.',
     '官方所说的“证据不足”不是背书。USPSTF 给复合维生素的是 I 级声明，'
     '意思是现有试验既不能证明有益，也不能排除有害。行业却把它当成背书来引用。'),

    ('No upper limit set means nobody has assessed it. It is a gap in the science, not a finding of safety. '
     'Most botanicals and every probiotic in this document fall into that gap.',
     '“未设定上限”的意思是没有人评估过。这是科学上的空白，不是安全性结论。'
     '本文中的多数植物类产品和全部益生菌都落在这个空白里。'),

    ('Risk ratios below 1 mean fewer events, above 1 mean more events. When the confidence interval crosses 1, '
     'no effect was demonstrated. That is the entire logic of Figure 5.',
     '风险比小于 1 表示事件更少，大于 1 表示事件更多。当置信区间跨过 1 时，说明没有证明出效应。'
     '图 5 的全部逻辑就是这一条。'),

    ('Relative reductions are not absolute reductions. REDUCE-IT is quoted everywhere as a 25% reduction. '
     'The absolute reduction was 4.8 percentage points over 4.9 years, meaning about 21 people take the drug for one to benefit.',
     '相对下降不等于绝对下降。REDUCE-IT 到处被引用为“下降 25%”。'
     '而绝对下降是 4.9 年里的 4.8 个百分点，也就是约 21 个人服药才有 1 个人获益。'),

    ('The number on a mineral label is usually the compound, not the mineral. Magnesium oxide is about 60% magnesium, '
     'magnesium citrate about 16%. A capsule labelled 500 mg magnesium citrate delivers roughly 80 mg of magnesium.',
     '矿物质标签上的数字通常是化合物的量，不是矿物质本身的量。氧化镁约含 60% 的镁，柠檬酸镁约 16%。'
     '一粒标着“柠檬酸镁 500 毫克”的胶囊，实际提供的镁约为 80 毫克。'),

    ('The safety record of a food does not transfer to a concentrated extract of it. Drinking green tea is fine. '
     'Green tea extract has caused more than 100 published cases of liver injury, 8% of which went to transplant.',
     '一种食物的安全记录，不会自动转移到它的浓缩提取物上。喝绿茶没问题。'
     '绿茶提取物已造成 100 例以上公开报告的肝损伤，其中 8% 走到了肝移植。'),

    ('A certification mark says nothing about whether the product works. USP Verified, NSF and Informed Sport all '
     'certify content and purity. None of them assesses efficacy, and USP Verified does not screen for substances banned in sport.',
     '认证标识对“产品有没有用”只字未提。USP Verified、NSF 和 Informed Sport 认证的都是成分与纯度。'
     '没有一个评估有效性，而且 USP Verified 并不筛查运动违禁物质。'),
]


def I(verdict, grade, name_en, name_zh, dose_en, dose_zh, who_en, who_zh, pros, cons, refs):
    return dict(verdict=verdict, grade=grade, en=name_en, zh=name_zh,
                dose_en=dose_en, dose_zh=dose_zh, who_en=who_en, who_zh=who_zh,
                pros=pros, cons=cons, refs=refs)


ITEMS = [

# ============================================================ TAKE
I(TAKE, 'A', 'Folic acid', '叶酸',
  '400 µg/d, from at least one month before conception. 4 mg/d if a previous pregnancy was affected.',
  '400 微克/天，至少从受孕前一个月开始。若既往有受累妊娠，则 4 毫克/天。',
  'Anyone capable of becoming pregnant.', '任何可能怀孕的人。',
  pros=[
    ('Neural tube defects RR 0.31 (95% CI 0.17-0.58) across 5 trials and 6,708 births. This is the strongest single result in the whole supplement literature.',
     '神经管缺陷 RR 0.31（95% CI 0.17-0.58），5 项试验、6708 例分娩。这是整个补充剂文献中最强的单项结果。'),
    ('The MRC Vitamin Study (n=1,817 high-risk women) showed a 72% protective effect at 4 mg/d.',
     'MRC 维生素研究（1817 名高危女性）在 4 毫克/天下显示 72% 的保护效应。'),
    ('Population fortification works at scale: US grain fortification prevents about 1,326 affected births per year.',
     '人群强化在规模上有效：美国面粉强化每年避免约 1326 例受累出生。'),
    ('Costs a few pounds a year. No meaningful downside at 400 µg.',
     '一年只要几英镑。在 400 微克剂量下没有实质性坏处。'),
  ],
  cons=[
    ('Never take it alone when B12 status is unknown. Folic acid corrects the anaemia of B12 deficiency while the neurological damage silently progresses. This is the stated basis of the upper limit.',
     'B12 状态不明时绝不要单独服用。叶酸会纠正 B12 缺乏引起的贫血，而神经损害在无声中继续加重。这正是设定上限的理由。'),
    ('High-dose folic acid plus B12 taken for cardiovascular reasons raised cancer incidence (HR 1.21) and cancer mortality (HR 1.38) in pooled Norwegian trials. That is a different product at a different dose for a different purpose, and it should not be confused with the 400 µg periconceptional dose.',
     '为心血管目的服用的大剂量叶酸加 B12，在挪威两项试验合并分析中升高了癌症发病（HR 1.21）和癌症死亡（HR 1.38）。那是另一个剂量、另一个目的下的另一种用法，不应与 400 微克的围孕期剂量混为一谈。'),
    ('Upper limit 1,000 µg/d of synthetic folate, which applies to supplements and fortified food but not to folate from whole food.',
     '合成叶酸上限 1000 微克/天，适用于补充剂和强化食品，不适用于天然食物中的叶酸。'),
  ],
  refs='Cochrane CD007950.pub3 (PMID 26662928); MRC PMID 1677062; Williams PMID 25590678; Ebbing PMID 19920236'),

I(TAKE, 'A', 'Vitamin D3 (cholecalciferol)', '维生素 D3（胆钙化醇）',
  '800-2,000 IU/d, taken daily. Never as an annual or monthly bolus.',
  '800 至 2000 IU/天，每日服用。绝不要按年或按月大剂量冲击给药。',
  'People with serum 25(OH)D below about 30 nmol/L: dark skin at high latitude, covered clothing, housebound, northern-European winter.',
  '血清 25(OH)D 低于约 30 nmol/L 的人：高纬度地区的深肤色人群、遮盖式着装者、久不出门者、北欧的冬季。',
  pros=[
    ('Correcting genuine deficiency is real medicine: it treats rickets and osteomalacia, and no other intervention does.',
     '纠正真正的缺乏是实打实的治疗：它能治佝偻病和骨软化症，没有别的干预能做到这一点。'),
    ('With calcium, it cuts hip fracture in frail institutionalised elderly, RR 0.84 (0.74-0.96) across 9 trials and 49,853 people.',
     '与钙合用，可降低体弱的养老机构老人的髋部骨折，RR 0.84（0.74-0.96），9 项试验、49853 人。'),
    ('Deficiency is genuinely common in the target groups: 17.5% of non-Hispanic Black Americans are below 30 nmol/L versus 2.1% of white Americans, and 17.7% of Europeans are below it in the October to March window.',
     '在目标人群中，缺乏确实普遍：非西班牙裔黑人美国人中 17.5% 低于 30 nmol/L，白人为 2.1%；欧洲人在 10 月至次年 3 月这段时间有 17.7% 低于该值。'),
    ('Costs almost nothing. Generic D3 at 1,000 IU is a few pounds a year.',
     '几乎不花钱。1000 IU 的普通 D3 一年只要几英镑。'),
  ],
  cons=[
    ('It does not prevent cancer or cardiovascular disease. VITAL (n=25,871, 5.3 years): invasive cancer HR 0.96 (0.88-1.06), major cardiovascular events HR 0.97 (0.85-1.12). D-Health (n=21,315): all-cause mortality HR 1.04. ViDA (n=5,108): cardiovascular disease HR 1.02.',
     '它不能预防癌症或心血管病。VITAL（n=25871，5.3 年）：浸润性癌 HR 0.96（0.88-1.06），主要心血管事件 HR 0.97（0.85-1.12）。D-Health（n=21315）：全因死亡 HR 1.04。ViDA（n=5108）：心血管病 HR 1.02。'),
    ('Vitamin D alone does nothing for fractures. Cochrane: hip fracture RR 1.12 (0.98-1.29) without calcium. The calcium is doing the work.',
     '单用维生素 D 对骨折毫无作用。Cochrane：不加钙时髋部骨折 RR 1.12（0.98-1.29）。起作用的是钙。'),
    ('More is actively worse, and this is the least-marketed finding in the field. Annual 500,000 IU increased falls (IRR 1.15) and fractures (IRR 1.26). Monthly 60,000 IU raised the proportion of people falling from 47.9% to 66.9%. Three years at 4,000 or 10,000 IU/d caused dose-dependent LOSS of radial bone density versus 400 IU/d.',
     '剂量越大反而越糟，而这是该领域最少被宣传的发现。每年 50 万 IU 增加跌倒（IRR 1.15）和骨折（IRR 1.26）。每月 6 万 IU 使跌倒人群比例从 47.9% 升到 66.9%。每天 4000 或 10000 IU 连服三年，桡骨骨密度相对 400 IU/天出现剂量依赖性的下降。'),
    ('The 30 ng/mL threshold that drives most deficiency marketing came from the Endocrine Society, and that society walked it back in 2024. Its current guideline suggests against routine testing in healthy adults and against empiric supplementation above the reference intake in healthy under-75s.',
     '推动大部分“缺乏”营销的 30 ng/mL 阈值来自内分泌学会，而该学会在 2024 年已经收回了这个说法。其现行指南建议：健康成人不必常规检测，75 岁以下健康人也不建议在参考摄入量之上经验性补充。'),
    ('Contraindicated in hypercalcaemia, primary hyperparathyroidism and granulomatous disease such as sarcoidosis or tuberculosis. Upper limit 4,000 IU/d.',
     '高钙血症、原发性甲状旁腺功能亢进、以及结节病或结核等肉芽肿性疾病禁用。上限 4000 IU/天。'),
  ],
  refs='VITAL PMID 30415629; D-Health PMID 35026158; ViDA PMID 28384800; Cochrane PMID 24729336; Herrick PMID 31076739; Cashman PMID 26864360; Endocrine Society PMID 38828931; Sanders PMID 20460620; Bischoff-Ferrari PMID 26747333; Burt PMID 31454046'),

I(TAKE, 'B', 'Vitamin B12 (cobalamin)', '维生素 B12（钴胺素）',
  '50-250 µg/d, or 1,000-2,000 µg once or twice weekly. Deficiency treatment: 1,000-2,000 µg/d orally.',
  '50 至 250 微克/天，或每周 1 至 2 次、每次 1000 至 2000 微克。治疗缺乏：口服 1000 至 2000 微克/天。',
  'Vegans and long-term vegetarians, metformin users, people on a proton pump inhibitor for over two years, post-bariatric patients, pernicious anaemia.',
  '纯素与长期素食者、二甲双胍使用者、服用质子泵抑制剂超过两年者、减重手术后患者、恶性贫血患者。',
  pros=[
    ('The deficiency is real and the neurological damage is irreversible once established, so correcting it early genuinely matters.',
     '这种缺乏是真实存在的，一旦形成，神经损害不可逆，所以及早纠正确实要紧。'),
    ('Oral works as well as injection. Cochrane found 1,000 µg/d oral matched intramuscular, and at 2,000 µg/d oral was better by 680 pg/mL. Injections are a business model.',
     '口服和注射一样好。Cochrane 发现口服 1000 微克/天与肌注相当，2000 微克/天时口服还高出 680 pg/mL。打针是一门生意。'),
    ('Risk in the named groups is well quantified: metformin lowers B12 by 19% over 4.3 years; two or more years of PPI use gives OR 1.65.',
     '上述人群的风险已被量化得很清楚：二甲双胍在 4.3 年内使 B12 下降 19%；使用 PPI 两年以上 OR 为 1.65。'),
    ('No tolerable upper intake level has been needed, because no adverse effect has been found from excess.',
     '至今不需要设定可耐受上限，因为没有发现过量带来的不良反应。'),
  ],
  cons=[
    ('It does nothing for energy, mood or cognition in people who are not deficient. That is the entire marketing claim and it has no support.',
     '对不缺乏的人，它在精力、情绪和认知上毫无作用。而这恰恰是它全部的营销卖点，且毫无依据。'),
    ('Do not treat with folate alone if B12 status is unknown, for the reason given under folic acid.',
     'B12 状态不明时不要单用叶酸治疗，理由见叶酸条目。'),
    ('Cyanocobalamin should be avoided in Leber hereditary optic neuropathy and in renal failure. Use hydroxocobalamin instead.',
     'Leber 遗传性视神经病变和肾衰竭者应避免氰钴胺，改用羟钴胺。'),
    ('High-dose biotin in the same B-complex product interferes with immunoassays including troponin, which can mimic or mask a heart attack on a blood test.',
     '同一款复合 B 族产品中的大剂量生物素会干扰包括肌钙蛋白在内的免疫检测，可能在化验上模仿或掩盖心肌梗死。'),
  ],
  refs='Cochrane PMID 29543316; de Jager BMJ 2010 PMID 20488910; Lam JAMA 2013 PMID 24327038; Pawlak review'),

I(TAKE, 'A', 'Iron', '铁',
  'Test ferritin first. Treatment 60-120 mg elemental iron. Ferrous sulfate 325 mg delivers 65 mg elemental.',
  '先查铁蛋白。治疗剂量为元素铁 60 至 120 毫克。硫酸亚铁 325 毫克提供 65 毫克元素铁。',
  'Menstruating women with ferritin at or below about 50 µg/L, pregnancy, blood donors, post-bariatric patients.',
  '铁蛋白在约 50 微克/升及以下的经期女性、孕妇、献血者、减重手术后患者。',
  pros=[
    ('Grade A for treating iron-deficiency anaemia and for pregnancy outcomes, across 57 trials and 48,971 women.',
     '在治疗缺铁性贫血和改善妊娠结局上属 A 级，涵盖 57 项试验、48971 名女性。'),
    ('Fatigue improves in non-anaemic iron-deficient women, but only below a ferritin threshold of about 50 µg/L. Above that, nothing happens.',
     '在无贫血但缺铁的女性中疲劳会改善，但仅限于铁蛋白低于约 50 微克/升。高于这个值就没有变化。'),
    ('Cheap and generic. Ferrous sulfate is the reference standard and there is no evidence that premium salts work better.',
     '便宜且通用。硫酸亚铁是参照标准，没有证据表明高价盐型更有效。'),
  ],
  cons=[
    ('Alternate-day dosing is oversold. The absorption physiology is real (21.8% versus 16.3% fractional absorption) but the only adequately sized randomised trial with haemoglobin as the endpoint found the same final ferritin either way. Treat it as a tolerability strategy, not a superiority one.',
     '隔日给药被过度宣传。吸收生理学是真的（分次吸收率 21.8% 对 16.3%），但唯一以血红蛋白为终点、样本量足够的随机试验显示两种方案最终铁蛋白相同。把它当作改善耐受性的办法，而不是更有效的办法。'),
    ('Never supplement anaemia that has not been shown to be iron-deficient. Anaemia of inflammation and haemochromatosis both get worse. Unexplained anaemia in an adult needs investigation, not a pill.',
     '绝不要对未证实是缺铁的贫血补铁。炎症性贫血和血色病都会因此加重。成年人不明原因的贫血需要检查，而不是吃药。'),
    ('Contraindicated in hereditary haemochromatosis (HFE C282Y homozygotes) and in transfusion-dependent anaemias such as thalassaemia and myelodysplastic syndrome.',
     '遗传性血色病（HFE C282Y 纯合子）以及地中海贫血、骨髓增生异常综合征等依赖输血的贫血禁用。'),
    ('Acute iron overdose was historically a leading cause of fatal poisoning in children under six, which is why unit-dose packaging exists. Keep it locked away.',
     '急性铁过量在历史上曾是六岁以下儿童致死性中毒的主要原因之一，单剂量包装正是因此而来。要锁好放置。'),
    ('Gastrointestinal side effects are the main reason people stop. Upper limit 45 mg/d (US); EFSA sets no limit but a safe level of 40 mg/d.',
     '胃肠道副作用是人们停药的主要原因。美国上限 45 毫克/天；EFSA 未设上限，但给出 40 毫克/天的安全水平。'),
  ],
  refs='Cochrane 2024; Stoffel PMID 29032957; von Siebenthal PMID 38021373; Verdon BMJ 2003'),

I(TAKE, 'A', 'Iodine', '碘',
  '150 µg/d as potassium iodide. 250 µg/d in pregnancy and lactation (WHO).',
  '碘化钾形式 150 微克/天。妊娠期与哺乳期 250 微克/天（WHO）。',
  'Preconception, pregnancy and lactation, vegans, and anyone avoiding both dairy and fish.',
  '备孕、孕期与哺乳期、纯素者，以及同时回避乳制品和鱼类的人。',
  pros=[
    ('Universal salt iodisation is the single most successful micronutrient intervention in public health, and it works because iodine is the sole substrate for thyroid hormone.',
     '全民食盐加碘是公共卫生史上最成功的微量营养素干预，它之所以有效，是因为碘是甲状腺激素唯一的合成原料。'),
    ('The deficiency has quietly returned in the UK and parts of Europe. UK schoolgirls had a median urinary iodine of 80.1 µg/L against a WHO adequacy threshold of 100, with 51% mildly deficient.',
     '这种缺乏在英国和欧洲部分地区已悄然回潮。英国女学生尿碘中位数为 80.1 微克/升，而 WHO 的充足阈值是 100，其中 51% 属轻度缺乏。'),
    ('The requirement rises about 50% in pregnancy, and the window for fetal brain development does not reopen.',
     '妊娠期需求上升约 50%，而胎儿脑发育的窗口一旦错过就不再打开。'),
  ],
  cons=[
    ('Correcting status during pregnancy may be too late. MITCH randomised 832 mildly deficient pregnant women to 200 µg/d and found a verbal IQ difference of -0.7 in their children at age 5-6. Fix it before conception.',
     '在孕期才纠正可能已经太晚。MITCH 试验把 832 名轻度缺碘孕妇随机分到 200 微克/天，其子女在 5 至 6 岁时言语智商差异为 -0.7。要在受孕前解决。'),
    ('Avoid kelp and bladderwrack entirely. Content is wildly variable and can deliver many times the upper limit in a single dose.',
     '完全避开海带和墨角藻。其含量极不稳定，单次剂量就可能达到上限的许多倍。'),
    ('An iodine load can precipitate iodine-induced hyperthyroidism in autonomous thyroid nodules or multinodular goitre, and can cause hypothyroidism in autoimmune thyroid disease. Anyone with a thyroid history needs medical advice first.',
     '在自主功能性甲状腺结节或多结节性甲状腺肿中，碘负荷可诱发碘致甲亢；在自身免疫性甲状腺病中则可能导致甲减。有甲状腺病史者必须先咨询医生。'),
    ('Upper limit 1,100 µg/d (US) but only 600 µg/d (EFSA).',
     '美国上限 1100 微克/天，而 EFSA 只有 600 微克/天。'),
  ],
  refs='Vanderpump Lancet 2011 PMID 21640375; MITCH PMID 29030199; Cochrane PMID 28260263'),

I(TAKE, 'A', 'Creatine monohydrate', '一水肌酸',
  '3-5 g/d. Loading is optional: 20 g/d for 6 days and 3 g/d for 28 days reach the same muscle saturation.',
  '3 至 5 克/天。冲击期可有可无：20 克/天服 6 天与 3 克/天服 28 天，肌肉饱和程度相同。',
  'Anyone doing resistance training, and older adults in particular. Also vegetarians and vegans, whose baseline stores are lower.',
  '任何做抗阻训练的人，尤其是老年人。此外还有素食者和纯素者，他们的基础储备更低。',
  pros=[
    ('The best-evidenced ergogenic aid on the market. In older adults doing resistance training, +1.37 kg lean tissue mass (95% CI 0.97-1.76) over training alone, across 22 randomised trials.',
     '市面上证据最扎实的运动增效补剂。在做抗阻训练的老年人中，比单纯训练多增加 1.37 公斤瘦体重（95% CI 0.97-1.76），来自 22 项随机试验。'),
    ('Extremely cheap. Monohydrate costs pennies per dose and is the form used in essentially every trial.',
     '极其便宜。一水肌酸每次的成本只有几便士，而且几乎所有试验用的都是这个形式。'),
    ('Long safety record: no signal of harm in healthy kidneys across years of use in trials.',
     '安全记录长：在肾功能正常者中，多年的试验使用未见危害信号。'),
  ],
  cons=[
    ('The cognition claim is weaker than the marketing. Pooled memory effect SMD 0.31 (0.18-0.44), and EFSA formally concluded in 2024 that a cause-and-effect relationship with cognitive function has NOT been established.',
     '认知方面的说法远弱于营销。记忆的合并效应 SMD 0.31（0.18-0.44），而 EFSA 在 2024 年正式认定，与认知功能的因果关系尚未成立。'),
    ('Do not pay for HCl, buffered, liquid or micronised premium forms. They are price increases with no comparative evidence behind them.',
     '不要为盐酸盐、缓冲型、液态或“微粒化”高端形式付钱。它们只是涨价，背后没有对照证据。'),
    ('Existing chronic kidney disease or dialysis requires nephrology supervision, because the safety data are in healthy kidneys only.',
     '已有慢性肾病或在透析者需在肾科监督下使用，因为安全数据只来自肾功能正常的人。'),
    ('Expect 1-2 kg of water weight in the first weeks. That is intracellular water, not fat, but it matters if you compete in a weight class.',
     '头几周会增加 1 至 2 公斤水重。那是细胞内水分而非脂肪，但如果你参加分级别的比赛，这一点很要紧。'),
    ('No official upper limit exists. The commonly quoted safety envelope comes from an industry-affiliated position stand, and the actual sentence is absence of evidence of harm rather than demonstrated safety.',
     '没有官方上限。常被引用的安全区间来自一份与行业有关联的立场声明，而其原话是“没有证据显示有害”，而不是“已证明安全”。'),
  ],
  refs='Kreider PMID 28615996; Hultman PMID 8828669; Chilibeck PMID 29138605; Xu Front Nutr 2024; EFSA PMID 39564533'),

I(TAKE, 'A', 'Protein powder', '蛋白粉',
  'Whatever brings total daily protein to about 1.6 g/kg. The powder itself has no special property.',
  '补到每日总蛋白约 1.6 克/公斤即可。粉末本身没有任何特殊之处。',
  'People doing resistance training who are currently falling short of 1.6 g/kg/d from food.',
  '正在做抗阻训练、且靠食物达不到 1.6 克/公斤/天的人。',
  pros=[
    ('The nutrient is Grade A. Protein supplementation on top of resistance training adds 2.49 kg to 1RM strength and 0.30 kg of fat-free mass across 49 randomised trials and 1,863 people.',
     '作为营养素属 A 级。在抗阻训练之外补充蛋白，49 项随机试验、1863 人的数据显示 1RM 力量增加 2.49 公斤、去脂体重增加 0.30 公斤。'),
    ('The dose-response is precisely mapped: fat-free mass gains plateau at 1.62 g/kg/d, so you know exactly when to stop paying for more.',
     '量效关系被测得很精确：去脂体重的增益在 1.62 克/公斤/天见顶，所以你清楚知道从哪里开始不必再多花钱。'),
    ('Convenient and shelf-stable, which is a real advantage for people who cannot cook three protein-containing meals.',
     '方便、耐储存，对做不到三餐都有蛋白的人来说，这是实实在在的好处。'),
    ('Kidney fear is unfounded in healthy people. The reassuring data are solid, though they apply to healthy kidneys only.',
     '在健康人身上，对肾脏的担心没有根据。这方面的数据扎实，但只适用于肾功能正常者。'),
  ],
  cons=[
    ('The benefit is real and small. Three hundred grams of extra muscle over months of training is what the meta-analysis actually found. Food protein does the same job.',
     '收益真实但很小。meta 分析真正得到的，是数月训练后多出的 300 克肌肉。食物蛋白能起同样的作用。'),
    ('Branched-chain amino acids sold alongside are redundant and mechanistically incoherent. No human study has ever quantified muscle protein synthesis from oral BCAAs alone, and both intravenous studies found BCAAs DECREASED it. A 25 g whey serving already contains 5-6 g of BCAAs plus the six essential amino acids BCAAs lack.',
     '与之一同销售的支链氨基酸既多余，机制上也说不通。从没有人体研究定量过单独口服 BCAA 对肌蛋白合成的作用，而仅有的两项静脉研究都发现 BCAA 反而降低了合成。一份 25 克乳清本身就含 5 至 6 克 BCAA，外加 BCAA 所缺的那六种必需氨基酸。'),
    ('Heavy-metal loading is a genuine issue in plant and organic powders, which carry more cadmium and lead than whey. Third-party testing matters here more than in most categories.',
     '植物蛋白和有机蛋白粉的重金属负荷是个真问题，其镉和铅含量高于乳清。在这个品类里，第三方检测比多数品类都重要。'),
    ('Chronic kidney disease stage 3 or above requires a renal dietitian to set the protein prescription.',
     '慢性肾病 3 期及以上，蛋白摄入量必须由肾科营养师制定。'),
  ],
  refs='Morton PMID 28698222; Jager PMID 28642676; Wolfe PMID 28852372; Kato PMID 27322029'),

I(TAKE, 'B', 'Psyllium husk (ispaghula)', '洋车前子壳',
  'About 10 g/d, always with a full glass of fluid. Separate from other oral drugs by about two hours.',
  '约 10 克/天，务必配一整杯水。与其他口服药间隔约两小时。',
  'People with raised LDL cholesterol, irritable bowel syndrome of either subtype, or chronic constipation.',
  '低密度脂蛋白胆固醇偏高者、任一亚型的肠易激综合征患者、慢性便秘者。',
  pros=[
    ('LDL cholesterol falls 0.33 mmol/L (95% CI -0.38 to -0.27) at a median 10.2 g/d across 28 trials, and the apolipoprotein B evidence is graded HIGH quality, which is rare anywhere in this field.',
     '28 项试验、中位剂量 10.2 克/天下，低密度脂蛋白胆固醇下降 0.33 mmol/L（95% CI -0.38 至 -0.27），且载脂蛋白 B 的证据被评为高质量，这在整个领域都很少见。'),
    ('Irritable bowel syndrome: relative risk of persistent symptoms 0.83 (0.73-0.94), NNT 7. Very few gut products have a number this good.',
     '肠易激综合征：症状持续的相对风险 0.83（0.73-0.94），NNT 7。肠道类产品里很少有这么漂亮的数字。'),
    ('Cheap, generic and unglamorous, which is why it is under-sold rather than over-sold.',
     '便宜、通用、毫不起眼，正因如此它是被低估而不是被过度营销的。'),
    ('Works in both constipation-predominant and diarrhoea-predominant IBS, because it is a gel-forming fibre rather than a stimulant.',
     '在便秘型和腹泻型肠易激中都有效，因为它是形成凝胶的纤维，而不是刺激性泻剂。'),
  ],
  cons=[
    ('No hard-outcome trial exists. The LDL reduction is a surrogate endpoint, so nobody has shown psyllium prevents a heart attack.',
     '没有硬终点试验。低密度脂蛋白的下降是替代终点，没有人证明过洋车前子能预防心肌梗死。'),
    ('Contraindicated in dysphagia and in known or suspected bowel obstruction, stricture, impaction or ileus. This is an explicit FDA contraindication, not a formality.',
     '吞咽困难，以及已知或疑似的肠梗阻、狭窄、粪嵌塞或肠麻痹禁用。这是 FDA 明确列出的禁忌，不是走过场。'),
    ('It must be taken with enough fluid. Bed-bound patients with poor fluid intake should not use it.',
     '必须配足够的液体服用。卧床且饮水少的患者不应使用。'),
    ('It delays absorption of other oral drugs taken at the same time, which matters for narrow-therapeutic-index medicines.',
     '它会延迟同时服用的其他口服药的吸收，这对治疗窗窄的药物很要紧。'),
    ('Wheat bran, sold beside it under identical digestive-health signage, is a different product and is null in IBS (RR 0.90) and often makes it worse. Do not substitute.',
     '摆在旁边、挂着同样“肠道健康”招牌的麦麸是另一种东西，在肠易激中无效（RR 0.90），还常常加重症状。不要替换。'),
  ],
  refs='Jovanovski PMID 30239559; Moayyedi PMID 25070054; Bijkerk BMJ 2009 PMID 19713235; Reynolds Lancet 2019 PMID 30638909'),

I(TAKE, 'A', 'Caffeine', '咖啡因',
  '3-6 mg/kg body mass, about 60 minutes before exercise. For a 70 kg person that is 210-420 mg.',
  '按体重 3 至 6 毫克/公斤，运动前约 60 分钟服用。70 公斤的人为 210 至 420 毫克。',
  'Almost anyone training, trained or untrained. Also shift workers and the sleep-deprived, for the separate alertness effect.',
  '几乎所有训练的人，无论是否受过训练。此外还有轮班工作者和睡眠不足者，用的是另一个提高警觉的效应。',
  pros=[
    ('The most reliably ergogenic legal substance in this document. An umbrella review of 11 systematic reviews containing 21 meta-analyses, all of moderate or high quality, found benefit for aerobic endurance, strength, muscle endurance, power, jumping and speed.',
     '本文中最可靠的合法运动增效物质。一项涵盖 11 篇系统综述、21 项 meta 分析的伞式综述（全部为中高质量）显示，对有氧耐力、力量、肌耐力、爆发力、弹跳和速度均有益。'),
    ('Cheap, well characterised, and the dose-response is known.',
     '便宜、特性清楚，量效关系已知。'),
    ('The mechanism is central rather than metabolic, so it works by reducing perceived effort and pain, which is why it helps across so many different tasks.',
     '其机制是中枢性而非代谢性的，通过降低主观用力感和疼痛感起作用，这也是它在如此多不同任务上都有效的原因。'),
  ],
  cons=[
    ('Genotype changes the sign of the effect. CYP1A2 AA carriers gain (SMD 0.30), AC carriers gain a little (0.16), and CC carriers get WORSE (SMD -0.22). Most people do not know their genotype.',
     '基因型会改变效应的方向。CYP1A2 的 AA 型获益（SMD 0.30），AC 型略有获益（0.16），而 CC 型表现变差（SMD -0.22）。多数人并不知道自己的基因型。'),
    ('9 mg/kg brings a high incidence of side effects with no added benefit. More is not better past 6 mg/kg.',
     '9 毫克/公斤会带来大量副作用而没有额外收益。超过 6 毫克/公斤就不是越多越好。'),
    ('The fat-burner claim is the oversold part of the category. Thermogenesis is real and trivial.',
     '“燃脂”是这个品类里被过度吹嘘的部分。产热效应真实但微不足道。'),
    ('Contraindicated or needing care in uncontrolled hypertension, arrhythmia, anxiety and panic disorder. EFSA caps pregnancy at 200 mg/d, and derives no safe intake for children.',
     '未控制的高血压、心律失常、焦虑症和惊恐障碍者禁用或需谨慎。EFSA 把妊娠期上限定在 200 毫克/天，对儿童则无法推导出安全摄入量。'),
    ('Fluvoxamine is a potent CYP1A2 inhibitor and can raise caffeine exposure severalfold. Taken late, it damages the sleep that training depends on.',
     '氟伏沙明是强效 CYP1A2 抑制剂，可使咖啡因暴露量成倍升高。服用时间太晚则会损害训练所依赖的睡眠。'),
  ],
  refs='Guest ISSN PMID 33388079; Grgic PMID 30926628; Barreto PMID 37844569; EFSA J 2015;13(5):4102'),

I(TAKE, 'B', 'Omega-3 (EPA and DHA)', 'Omega-3（EPA 与 DHA）',
  '4 g/d of prescription-grade product if fasting triglycerides are at or above 500 mg/dL. Otherwise eat oily fish.',
  '若空腹甘油三酯达到或超过 500 mg/dL，用处方级产品 4 克/天。否则请吃多脂鱼。',
  'People with severe hypertriglyceridaemia. Separately, pregnant women with genuinely low baseline DHA, and people who eat essentially no fish.',
  '重度高甘油三酯血症患者。另外还有基础 DHA 确实偏低的孕妇，以及基本不吃鱼的人。',
  pros=[
    ('Triglyceride lowering is genuine pharmacology: 4 g/d cuts triglycerides by at least 30% in severe hypertriglyceridaemia, and the AHA endorses this specific indication.',
     '降甘油三酯是实打实的药理作用：在重度高甘油三酯血症中，4 克/天至少降低 30%，美国心脏协会明确支持这一适应证。'),
    ('REDUCE-IT was strongly positive in statin-treated patients with established cardiovascular disease: primary composite 17.2% versus 22.0%, HR 0.75 (0.68-0.83), an absolute reduction of 4.8 percentage points over 4.9 years.',
     'REDUCE-IT 在已服他汀且患有心血管病的人群中结果强阳性：主要复合终点 17.2% 对 22.0%，HR 0.75（0.68-0.83），4.9 年内绝对下降 4.8 个百分点。'),
    ('Pregnancy: Cochrane found preterm birth before 37 weeks RR 0.89 (0.81-0.97) and before 34 weeks RR 0.58 (0.44-0.77), both graded high quality, across 70 trials and 19,927 women.',
     '妊娠期：Cochrane 在 70 项试验、19927 名女性中发现，37 周前早产 RR 0.89（0.81-0.97），34 周前早产 RR 0.58（0.44-0.77），两项均被评为高质量。'),
  ],
  cons=[
    ('It does not prevent cardiovascular disease at supplement doses. Cochrane, 86 trials and 162,796 people: all-cause mortality RR 0.97 (0.93-1.01) at HIGH certainty, stroke RR 1.02. VITAL and ASCEND both missed their primary endpoints at 1 g/d.',
     '在补充剂剂量下，它不能预防心血管病。Cochrane 纳入 86 项试验、162796 人：全因死亡 RR 0.97（0.93-1.01），高确定性；卒中 RR 1.02。VITAL 和 ASCEND 在 1 克/天下都未达主要终点。'),
    ('The two big high-dose trials contradict each other. STRENGTH tested 4 g/d of EPA plus DHA against corn oil in 13,078 people and was flatly null (HR 0.99), stopped for futility. REDUCE-IT used a mineral-oil placebo that raised LDL, apolipoprotein B and hs-CRP in the control arm, so part of its 25% may be placebo-arm harm. Quote both trials or neither.',
     '两项大型高剂量试验互相矛盾。STRENGTH 在 13078 人中用 4 克/天的 EPA 加 DHA 对比玉米油，结果完全阴性（HR 0.99），因无效终止。REDUCE-IT 用的矿物油安慰剂使对照组的低密度脂蛋白、载脂蛋白 B 和超敏 C 反应蛋白升高，因此那 25% 中可能有一部分来自对照组受损。要引就两项一起引，否则一项也别引。'),
    ('Atrial fibrillation risk rises with dose: HR 1.25 (1.07-1.46), dose-dependent across 7 trials. Prior atrial fibrillation is a reason to stay away.',
     '房颤风险随剂量上升：7 项试验中 HR 1.25（1.07-1.46），呈剂量依赖。有房颤史就是不该用的理由。'),
    ('Bleeding risk on warfarin, direct oral anticoagulants, aspirin and clopidogrel. REDUCE-IT showed serious bleeding 2.7% versus 2.1%.',
     '与华法林、直接口服抗凝药、阿司匹林和氯吡格雷合用有出血风险。REDUCE-IT 中严重出血为 2.7% 对 2.1%。'),
    ('Product quality is poor. Half of North American products exceeded voluntary oxidation limits, and 38% of Australian products exceeded primary oxidation limits, with premium pricing giving no advantage. Buy encapsulated, unflavoured and in date.',
     '产品质量差。北美一半的产品超过自愿性氧化限值，澳大利亚 38% 的产品超过初级氧化限值，而高价并不带来优势。要买胶囊装、无调味、在有效期内的。'),
    ('Pregnancy is not straightforward either: ORIP (n=5,486, 900 mg/d) was null and showed excess very-large-for-gestational-age infants. Benefit concentrates in women with low baseline DHA.',
     '妊娠期也并不简单：ORIP（n=5486，900 毫克/天）为阴性，并出现超大于胎龄儿增多。获益集中在基础 DHA 偏低的女性身上。'),
  ],
  refs='Cochrane PMID 32114706; REDUCE-IT PMID 30415628; STRENGTH PMID 33190147; Gencer PMID 34612056; Cochrane pregnancy PMID 30480773; ORIP PMID 31509674; AHA PMID 31422671'),

# ============================================================ CONSIDER
I(CONSIDER, 'B', 'Magnesium', '镁',
  '365 mg/d elemental for blood pressure. Note magnesium oxide is 60% elemental, citrate 16%, bisglycinate 14%.',
  '降血压用元素镁 365 毫克/天。注意氧化镁含 60% 元素镁，柠檬酸镁 16%，甘氨酸螯合镁 14%。',
  'People with documented low magnesium, chronic proton pump inhibitor or diuretic users, alcohol use disorder, and treated hypertensives.',
  '已证实镁偏低者、长期使用质子泵抑制剂或利尿剂者、酒精使用障碍者、已在服药的高血压患者。',
  pros=[
    ('Blood pressure falls by a real amount in the right people: -5.97 mmHg systolic in the hypomagnesaemic and -7.68 mmHg in treated hypertensives.',
     '在合适的人身上血压确有下降：低镁血症者收缩压降 5.97 mmHg，已服药的高血压患者降 7.68 mmHg。'),
    ('Proton-pump-inhibitor-induced hypomagnesaemia is an established, under-recognised clinical problem that this genuinely fixes.',
     '质子泵抑制剂引起的低镁血症是一个确凿而常被忽视的临床问题，补镁确实能解决。'),
    ('Cheap, and dietary intake is genuinely low in many Western diets.',
     '便宜，而且在许多西方饮食中摄入量确实偏低。'),
  ],
  cons=[
    ('In replete normotensive people the pooled blood pressure effect did not reach significance. The general-population heart-health pitch is unsupported.',
     '在镁充足且血压正常的人中，合并的降压效应未达显著。面向普通人群的“护心”说法没有依据。'),
    ('The sleep claim, now the dominant marketing angle, rests on 3 trials and 151 older adults, all at moderate to high risk of bias, and the review authors called the literature substandard for making recommendations.',
     '如今主导营销的助眠说法，只建立在 3 项试验、151 名老年人之上，全部为中高偏倚风险，综述作者直言这些文献的质量不足以据此提出建议。'),
    ('The 600 mg/d migraine dose exceeds the US supplemental upper limit of 350 mg and is 2.4 times the EFSA limit of 250 mg. Diarrhoea is the dose-limiting effect.',
     '偏头痛用的 600 毫克/天超过美国 350 毫克的补充剂上限，是 EFSA 250 毫克上限的 2.4 倍。腹泻是剂量限制性反应。'),
    ('Contraindicated without supervision in chronic kidney disease stage 4-5 and dialysis, where hypermagnesaemia causes bradycardia, hypotension and respiratory depression. Also in myasthenia gravis.',
     '慢性肾病 4 至 5 期和透析患者未经监督禁用，高镁血症会导致心动过缓、低血压和呼吸抑制。重症肌无力同样禁用。'),
    ('Chelates tetracyclines, fluoroquinolones and bisphosphonates. Separate by 2-4 hours.',
     '会与四环素类、氟喹诺酮类和双膦酸盐螯合。间隔 2 至 4 小时。'),
  ],
  refs='Argeros Hypertension 2025 PMID 41000008; Mah & Pitre PMID 33865376; Peikert PMID 8792038'),

I(CONSIDER, 'B', 'Zinc lozenges', '锌含片',
  '75-100 mg/d elemental, split into 6-8 lozenges, started within 24 hours of symptom onset and stopped when symptoms resolve.',
  '元素锌 75 至 100 毫克/天，分 6 至 8 片含服，症状出现 24 小时内开始，症状消失即停。',
  'Someone at the very start of a cold who will actually follow the lozenge schedule.',
  '感冒刚起、且真的能按含片时间表执行的人。',
  pros=[
    ('Cold duration shortens. Hemila found -33% (21-45%) across lozenge trials, with no additional benefit above 100 mg/d.',
     '感冒病程会缩短。Hemila 在含片试验中得到 -33%（21-45%），且超过 100 毫克/天没有额外收益。'),
    ('Cheap, and the treatment window is short enough that the copper risk does not apply.',
     '便宜，而且疗程短到不会触发铜缺乏的风险。'),
    ('Zinc for acute childhood diarrhoea in deficient populations is a separate and much stronger indication, used as standard of care in low-income settings.',
     '在缺锌人群中用锌治疗儿童急性腹泻是另一个适应证，证据强得多，在低收入地区已是标准治疗。'),
  ],
  cons=[
    ('The evidence is genuinely contested, and honest reporting means saying so. Cochrane 2024 rated duration LOW certainty at -2.37 days, found prevention null and severity null. Hemila published a methodological rebuttal alleging Cochrane pooled a 190 mg/d lozenge trial with a 0.046 mg/d nasal trial, a 4,300-fold dose difference.',
     '证据确实存在争议，诚实的做法是把这一点说出来。Cochrane 2024 把病程缩短 2.37 天评为低确定性，并发现预防无效、严重程度无改善。Hemila 发表了方法学反驳，指出 Cochrane 把一项 190 毫克/天的含片试验与一项 0.046 毫克/天的鼻用试验合并，剂量相差 4300 倍。'),
    ('Chronic intake above 40 mg/d causes copper depletion, which produces sideroblastic anaemia, neutropenia and an irreversible myelopathy that mimics subacute combined degeneration. This is the reason the treatment must be short.',
     '长期摄入超过 40 毫克/天会造成铜缺乏，引起铁粒幼细胞性贫血、中性粒细胞减少，以及一种模仿亚急性联合变性的不可逆脊髓病。这正是疗程必须短的原因。'),
    ('Formulation matters and most retail lozenges are wrong. Citric acid and sorbitol bind zinc and stop it being released.',
     '剂型很关键，而多数零售含片是错的。柠檬酸和山梨醇会结合锌，使其无法释放。'),
    ('Chelates fluoroquinolones and tetracyclines. Nasal zinc caused permanent anosmia and should never be used.',
     '会与氟喹诺酮类和四环素类螯合。鼻用锌曾造成永久性嗅觉丧失，绝不可使用。'),
  ],
  refs='Cochrane Nault PMID 38719213; Hemila PMID 28515951; Hemila & Chalker PMID 39478818'),

I(CONSIDER, 'B', 'Melatonin', '褪黑素',
  '0.5-5 mg. Timing is the active ingredient, not dose. For phase advance, 0.5 mg taken 2-4 hours before dim-light melatonin onset.',
  '0.5 至 5 毫克。起作用的是服用时间，不是剂量。要提前相位，在暗光褪黑素起始前 2 至 4 小时服 0.5 毫克。',
  'Jet lag eastward across five or more time zones, delayed sleep-wake phase disorder, shift work, and blind people with free-running rhythms.',
  '向东跨越五个及以上时区的时差、睡眠时相延迟障碍、轮班工作，以及节律自由运转的盲人。',
  pros=[
    ('Circadian phase-shifting is real pharmacology with a mapped phase-response curve. For jet lag across five or more zones the NNT is 2, and 9 of 10 trials were positive.',
     '昼夜节律相位调整是真实的药理作用，其相位反应曲线已被测绘。对跨五个以上时区的时差，NNT 为 2，10 项试验中有 9 项阳性。'),
    ('In delayed sleep-wake phase disorder, sleep onset advanced by 0.67 hours and endogenous melatonin onset by 1.18 hours.',
     '在睡眠时相延迟障碍中，入睡时间提前 0.67 小时，内源性褪黑素起始提前 1.18 小时。'),
    ('Short-term safety is good and it is not habit-forming in the way sedatives are.',
     '短期安全性良好，也不像镇静剂那样形成依赖。'),
  ],
  cons=[
    ('For ordinary insomnia it barely does anything: 7 minutes off sleep latency and 8 minutes more total sleep across 19 trials and 1,683 people. The AASM guideline explicitly suggests clinicians NOT use it for insomnia.',
     '对普通失眠几乎没用：19 项试验、1683 人的数据是入睡潜伏期缩短 7 分钟、总睡眠时间增加 8 分钟。美国睡眠医学会指南明确建议临床不要用它治失眠。'),
    ('Retail dose accuracy is the worst documented in this document. 22 of 25 gummy products were inaccurately labelled, at 74-347% of the declared amount, and one product labelled 3 mg contained no melatonin at all but 31.3 mg of CBD. A separate analysis of 31 products found -83% to +478% of label and serotonin contamination in 8 of them.',
     '零售剂量准确度是本文中记录到最差的。25 个软糖产品中有 22 个标签不准确，实测为标示量的 74 至 347%，其中一个标注 3 毫克的产品完全不含褪黑素，却含 31.3 毫克 CBD。另一项对 31 个产品的分析发现含量为标示量的 -83% 至 +478%，其中 8 个检出血清素污染。'),
    ('Not for children. The gummy format plus up to 347% overdosing plus palatability is a bad combination.',
     '不要给儿童。软糖剂型、最高 347% 的超量、加上好吃，是很糟的组合。'),
    ('Retail doses of 5-10 mg are far above what the pharmacology needs and can shift the clock the wrong way if taken at the wrong time.',
     '零售常见的 5 至 10 毫克远高于药理所需，而且在错误的时间服用还会把生物钟推向错误的方向。'),
    ('Cochrane specifically flagged caution in people on warfarin and people with epilepsy. Fluvoxamine markedly raises melatonin exposure via CYP1A2 inhibition.',
     'Cochrane 特别提示华法林使用者和癫痫患者需谨慎。氟伏沙明通过抑制 CYP1A2 显著升高褪黑素暴露量。'),
  ],
  refs='Burgess PMID 20410229; van Geijlswijk PMID 21120122; Ferracioli-Oda PMID 23691095; Cohen JAMA 2023 PMID 37097362; Erland & Saxena PMID 27855744; Sateia AASM PMID 27998379'),

I(CONSIDER, 'B', 'Probiotics, named strain only', '益生菌，仅限指定菌株',
  'Antibiotic-associated diarrhoea in children: at least 5 billion CFU/d. C. difficile prevention: 10-50 billion CFU/d. Infant colic: L. reuteri DSM 17938 at 100 million CFU/d.',
  '儿童抗生素相关腹泻：至少 50 亿 CFU/天。预防艰难梭菌：100 至 500 亿 CFU/天。婴儿肠绞痛：罗伊氏乳杆菌 DSM 17938，1 亿 CFU/天。',
  'Children on a course of antibiotics, adults on antibiotics with elevated C. difficile risk, and exclusively breastfed infants with colic.',
  '正在用抗生素的儿童、艰难梭菌风险升高且在用抗生素的成人、以及纯母乳喂养的肠绞痛婴儿。',
  pros=[
    ('Paediatric antibiotic-associated diarrhoea: 8% versus 19%, RR 0.45 (0.36-0.56), NNT 9 at the higher dose. This is a genuinely useful number.',
     '儿童抗生素相关腹泻：8% 对 19%，RR 0.45（0.36-0.56），高剂量下 NNT 为 9。这是一个真正有用的数字。'),
    ('C. difficile prevention during antibiotics: RR 0.50 (0.38-0.64), 1.6% versus 3.2%.',
     '抗生素期间预防艰难梭菌：RR 0.50（0.38-0.64），1.6% 对 3.2%。'),
    ('Infant colic in exclusively breastfed babies: NNT 2.6 for treatment success at day 21, which is a striking number for a benign intervention with a defined stop point.',
     '纯母乳喂养婴儿的肠绞痛：第 21 天治疗成功的 NNT 为 2.6。对一个温和且有明确停用节点的干预来说，这个数字相当亮眼。'),
    ('Pouchitis maintenance after antibiotic-induced remission has a real randomised result: remission maintained in 17 of 20 versus 1 of 16.',
     '抗生素诱导缓解后的贮袋炎维持治疗有实实在在的随机结果：20 人中 17 人维持缓解，对照组 16 人中仅 1 人。'),
  ],
  cons=[
    ('The category claim is unfalsifiable marketing. Evidence attaches to a named strain at a defined dose. Disaggregate 82 trials and 10,332 IBS patients by strain and GRADE certainty collapses to low or very low almost everywhere.',
     '品类式声称是无法证伪的营销话术。证据只依附于特定菌株在特定剂量下的表现。把 82 项试验、10332 名肠易激患者按菌株拆开，GRADE 确定性几乎处处塌到低或极低。'),
    ('C. difficile prevention has NNT 65 at LOW certainty, so 64 of 65 people get nothing. The absolute benefit scales with baseline risk.',
     '预防艰难梭菌的 NNT 是 65，确定性为低，也就是 65 人中有 64 人什么也得不到。绝对获益随基线风险而变。'),
    ('The largest trial ever run was null. PLACIDE randomised 2,981 hospitalised patients over 65 and found no effect on either antibiotic-associated diarrhoea (RR 1.04) or C. difficile.',
     '规模最大的试验是阴性的。PLACIDE 随机了 2981 名 65 岁以上住院患者，对抗生素相关腹泻（RR 1.04）和艰难梭菌均无效应。'),
    ('The AGA recommends AGAINST probiotics for irritable bowel syndrome outside clinical trials.',
     '美国胃肠病学会建议，在临床试验之外不要用益生菌治疗肠易激综合征。'),
    ('There is a real harm signal in the critically ill. In predicted severe acute pancreatitis, mortality was 16% versus 6% (RR 2.53) with 9 cases of bowel ischaemia, 8 fatal, versus zero on placebo. The FDA also warned providers after a preterm infant died of probiotic-associated sepsis.',
     '在危重患者中存在真实的危害信号。在预测为重症急性胰腺炎的患者中，死亡率 16% 对 6%（RR 2.53），并出现 9 例肠缺血、其中 8 例死亡，安慰剂组为零。此外，在一名早产儿死于益生菌相关脓毒症后，FDA 也向医疗机构发出了警示。'),
    ('Absolute contraindications: central venous catheter, neutropenia, severe immunocompromise, critical illness, and preterm infants outside a supervised protocol.',
     '绝对禁忌：中心静脉置管、中性粒细胞减少、重度免疫抑制、危重症，以及未在监督方案内的早产儿。'),
  ],
  refs='Cochrane Guo PMID 31039287; Cochrane CD006095.pub5 PMID 40931979; Sung PMID 29279326; PLACIDE PMID 23932219; Goodoory & Ford PMID 37541528; AGA PMID 32531291; PROPATRIA PMID 18279948'),

I(CONSIDER, 'B', 'Berberine', '小檗碱',
  '500 mg two or three times daily with meals. Note dihydroberberine and phytosome forms are more bioavailable and are not milligram-equivalent.',
  '500 毫克，每日 2 至 3 次，随餐服用。注意二氢小檗碱和植物体形式生物利用度更高，毫克数不能等同换算。',
  'Adults with type 2 diabetes or prediabetes not reaching glycaemic targets, as an add-on, with a prescriber informed.',
  '2 型糖尿病或糖尿病前期、血糖未达标的成人，作为加用药物，且需告知处方医生。',
  pros=[
    ('The effect is real and clinically sized, which is unusual in this document: fasting glucose -0.82 mmol/L, HbA1c -0.63%, across 37 trials and 3,048 patients. That HbA1c reduction is in the range of a real drug.',
     '效应真实且具临床规模，这在本文中并不多见：空腹血糖降低 0.82 mmol/L，糖化血红蛋白降低 0.63%，来自 37 项试验、3048 名患者。这个糖化血红蛋白降幅已接近真正的药物。'),
    ('Total adverse events were lower than comparators in the pooled analysis (RR 0.73), and it does not cause hypoglycaemia on its own.',
     '在合并分析中总不良事件低于对照药（RR 0.73），且单用不引起低血糖。'),
  ],
  cons=[
    ('The marketing understates the pharmacology rather than overstating it, and that is the danger. This behaves like a drug and should be treated as one.',
     '它的营销是低估而不是高估了其药理作用，危险恰恰在这里。它的行为像药，就应当被当作药来对待。'),
    ('The most dangerous interaction in this document: 600 mg/d for three months raised ciclosporin trough concentrations by 88.9% in 52 renal transplant recipients. Note that this interaction dose is BELOW the typical glycaemic dose.',
     '本文中最危险的相互作用：52 名肾移植受者服用 600 毫克/天共三个月，环孢素谷浓度升高 88.9%。注意这个产生相互作用的剂量低于常规降糖剂量。'),
    ('Berberine alone showed no statistical advantage over lifestyle change. The benefit appears as an add-on to an existing oral hypoglycaemic.',
     '单用小檗碱相对生活方式干预没有统计学优势。获益体现在与已有口服降糖药联用时。'),
    ('The trial base is dominated by small Chinese trials that meta-analysts repeatedly describe as having low methodological quality.',
     '试验基础以小型中国试验为主，meta 分析作者反复指出其方法学质量偏低。'),
    ('No upper limit exists. Toxicology review reports dose-dependent gastrointestinal ulceration, immunotoxicity, phototoxicity, neurotoxicity and cardiotoxicity. Contraindicated in pregnancy and in neonates (kernicterus risk).',
     '没有设定上限。毒理学综述报告了剂量依赖的胃肠道溃疡、免疫毒性、光毒性、神经毒性和心脏毒性。妊娠期和新生儿禁用（核黄疸风险）。'),
  ],
  refs='Xie PMID 36467075; Lan PMID 25498346; Dong PMID 23118793; ciclosporin interaction PMID 16133554'),

I(CONSIDER, 'C', 'Vitamin C', '维生素 C',
  '200 mg/d if taken regularly. Higher doses do not shorten colds further and cause osmotic diarrhoea.',
  '若规律服用，200 毫克/天。更高剂量并不能进一步缩短感冒，反而引起渗透性腹泻。',
  'Smokers, heavy alcohol users, people on very restricted diets, and those under extreme physical stress such as marathon runners.',
  '吸烟者、大量饮酒者、饮食极度受限者，以及处于极端身体应激下的人，比如马拉松跑者。',
  pros=[
    ('It cures scurvy, which is an unambiguous deficiency disease, and scurvy still occurs in food-insecure and alcohol-dependent populations.',
     '它能治愈坏血病，这是一种毫不含糊的缺乏症，而坏血病在食物不安全和酒精依赖人群中至今仍会出现。'),
    ('Under extreme physical stress such as marathons and sub-arctic exercise, prophylactic vitamin C halved cold incidence. That subgroup effect is real.',
     '在马拉松、亚寒带运动等极端身体应激下，预防性补充维生素 C 使感冒发生率减半。这个亚组效应是真实的。'),
    ('Smokers genuinely need 35 mg/d more than non-smokers because of higher turnover.',
     '吸烟者由于周转率更高，确实比不吸烟者每天多需要 35 毫克。'),
  ],
  cons=[
    ('It does not prevent colds in the general population: RR 0.97 (0.94-1.00) across 29 comparisons and 11,306 people. This is the founding claim of the modern supplement industry and it is false.',
     '它不能预防普通人群的感冒：29 项比较、11306 人的数据是 RR 0.97（0.94-1.00）。这是现代补充剂行业的奠基性主张，而它是错的。'),
    ('Duration falls only 8% in adults and 14% in children, which is roughly half a day.',
     '病程在成人中只缩短 8%，儿童 14%，大约是半天。'),
    ('Intravenous vitamin C in sepsis is HARMFUL. The LOVIT trial (n=863) found more death or persistent organ dysfunction in the treatment arm.',
     '脓毒症静脉用维生素 C 是有害的。LOVIT 试验（n=863）发现治疗组死亡或持续器官功能障碍更多。'),
    ('Avoid with a history of calcium oxalate kidney stones or hyperoxaluria, and in renal impairment, because ascorbate is metabolised to oxalate.',
     '有草酸钙肾结石史或高草酸尿者、以及肾功能不全者应避免，因为抗坏血酸会代谢为草酸。'),
    ('Upper limit 2,000 mg/d, set on osmotic diarrhoea.',
     '上限 2000 毫克/天，依据是渗透性腹泻。'),
  ],
  refs='Cochrane Hemila PMID 23440782; LOVIT PMID 35704292'),

I(CONSIDER, 'B', 'Coenzyme Q10 / ubiquinol', '辅酶 Q10 / 泛醇',
  '100 mg three times daily, the Q-SYMBIO regimen. Ubiquinol is more bioavailable and doses do not transfer 1:1 from ubiquinone.',
  '100 毫克每日三次，即 Q-SYMBIO 方案。泛醇生物利用度更高，与泛醌之间剂量不能一比一换算。',
  'Patients with heart failure with reduced ejection fraction, already on guideline therapy, with cardiology input.',
  '射血分数降低的心衰患者，且已在接受指南推荐治疗，需心内科参与决定。',
  pros=[
    ('Q-SYMBIO is the only clinical-endpoint result in the whole longevity and metabolic category: n=420, 2 years, major adverse cardiovascular events 15% versus 26%, HR 0.50 (0.32-0.80).',
     'Q-SYMBIO 是整个抗衰老与代谢品类中唯一有临床终点的结果：n=420，2 年，主要不良心血管事件 15% 对 26%，HR 0.50（0.32-0.80）。'),
    ('Genuine primary CoQ10 deficiency is a real, rare condition where replacement is the treatment.',
     '真正的原发性辅酶 Q10 缺乏是一种真实存在的罕见病，替代治疗就是它的疗法。'),
  ],
  cons=[
    ('Q-SYMBIO is a single unreplicated trial. The NIHR health technology assessment covering 26 trials and 2,250 participants flagged important concerns about risk of bias, plausibility of effect sizes and applicability, and found all-cause mortality RR 0.68 (0.45-1.03), not significant.',
     'Q-SYMBIO 是一项未被重复验证的单一试验。NIHR 的卫生技术评估涵盖 26 项试验、2250 名受试者，对其偏倚风险、效应量的合理性和适用性提出重要质疑，并得出全因死亡 RR 0.68（0.45-1.03），不显著。'),
    ('For statin-associated muscle symptoms, which is where most retail CoQ10 is actually sold, it does nothing: weighted mean difference -0.42 (-1.47 to 0.62) and adherence RR 0.99 across 7 trials.',
     '在他汀相关肌痛这个零售辅酶 Q10 的真正主销场景上，它毫无作用：7 项试验的加权均数差为 -0.42（-1.47 至 0.62），依从性 RR 0.99。'),
    ('Warfarin interaction: CoQ10 is structurally similar to vitamin K, and one cross-sectional analysis of patients presenting with anticoagulant overdose found an association with bleeding.',
     '与华法林的相互作用：辅酶 Q10 结构上与维生素 K 相似，一项针对抗凝药过量就诊患者的横断面分析发现其与出血相关。'),
    ('Expensive relative to everything else in this document, and the 1,200 mg observed safe level comes from a risk assessment whose authors were affiliated with an industry trade body.',
     '相对本文中其他产品价格昂贵，而 1200 毫克的“观察安全水平”出自一份作者与行业协会有关联的风险评估。'),
  ],
  refs='Q-SYMBIO PMID 25282031; Kennedy PMID 32179207; Claxton NIHR HTA PMID 35076012'),

I(CONSIDER, 'B', 'Alpha-lipoic acid', '硫辛酸',
  '600 mg/d orally. The strong evidence is for the intravenous route at the same dose, which consumers cannot access.',
  '口服 600 毫克/天。强证据来自同剂量的静脉给药，而消费者无法使用这一途径。',
  'People with symptomatic diabetic distal symmetric polyneuropathy, specifically positive sensory symptoms such as burning and paraesthesia.',
  '有症状的糖尿病远端对称性多发性神经病患者，特别是有烧灼感、感觉异常等阳性感觉症状者。',
  pros=[
    ('Licensed as a drug for diabetic polyneuropathy in Germany, which is a higher bar than any supplement in this document clears.',
     '在德国作为糖尿病多发性神经病的药物获批，这个门槛高于本文中任何一款补充剂。'),
    ('The intravenous meta-analysis (4 trials, 1,258 patients) found consistent relief of positive neuropathic symptoms.',
     '静脉给药的 meta 分析（4 项试验、1258 名患者）发现对阳性神经病理性症状有一致的缓解。'),
    ('Secondary endpoints in the long oral trial did improve, including neuropathy impairment scores.',
     '长期口服试验的次要终点确有改善，包括神经病变损害评分。'),
  ],
  cons=[
    ('The definitive oral trial failed. NATHAN 1 randomised 460 patients to 600 mg/d for 4 years and missed its primary endpoint (P=0.105).',
     '决定性的口服试验失败了。NATHAN 1 把 460 名患者随机到 600 毫克/天，持续 4 年，未达主要终点（P=0.105）。'),
    ('Serious adverse events in that trial were 38.1% on alpha-lipoic acid versus 28.0% on placebo, an excess that is rarely mentioned in marketing.',
     '该试验中严重不良事件在硫辛酸组为 38.1%，安慰剂组为 28.0%，这个超出的部分在营销中几乎从不被提及。'),
    ('It is a leading trigger of insulin autoimmune syndrome (Hirata disease) in people carrying HLA-DRB1*04 alleles, producing anti-insulin antibodies and severe hypoglycaemia in non-diabetics. Almost nobody knows their HLA status.',
     '在携带 HLA-DRB1*04 等位基因的人中，它是胰岛素自身免疫综合征（平田病）的主要诱因之一，可产生抗胰岛素抗体并在非糖尿病者中引起严重低血糖。几乎没有人知道自己的 HLA 型别。'),
    ('No upper limit has been set by any authority.',
     '没有任何权威机构为其设定上限。'),
  ],
  refs='NATHAN 1 PMID 21775755; Ziegler IV meta-analysis PMID 14984445; BMJ Case Rep PMID 42493219'),

I(CONSIDER, 'C', 'Beta-alanine', 'β-丙氨酸',
  '4-6 g/d for at least 2-4 weeks, split into doses of about 1.6 g to limit paraesthesia. Total accumulated dose matters more than daily dose.',
  '4 至 6 克/天，至少持续 2 至 4 周，分成每次约 1.6 克以减少刺痛感。累积总量比每日剂量更重要。',
  'Athletes whose limiting factor is acidosis in the one to four minute window: middle distance, rowing, combat sports, high-repetition lifting.',
  '限制因素是 1 至 4 分钟区间酸中毒的运动员：中距离项目、赛艇、格斗类、高次数举重。',
  pros=[
    ('The mechanism is sound and confirmed: it raises intramuscular carnosine, which buffers protons.',
     '机制清楚且已被证实：它提高肌内肌肽含量，从而缓冲质子。'),
    ('The IOC consensus statement places buffering agents on its short list of supplements with robust performance evidence.',
     '国际奥委会共识声明把缓冲类物质列入其“具备可靠成绩证据”的短名单。'),
    ('Cheap, and paraesthesia aside, no established contraindication or drug interaction exists.',
     '便宜，而且除刺痛感外，没有已确立的禁忌或药物相互作用。'),
  ],
  cons=[
    ('The overall pooled effect is SMD 0.18 (0.08-0.28) across 40 studies and 1,461 people. Statistically significant and practically tiny.',
     '40 项研究、1461 人的总体合并效应是 SMD 0.18（0.08-0.28）。统计学显著，实际微乎其微。'),
    ('In the 0.5 to 10 minute window where it should work best, exercise CAPACITY improved (SMD 0.50) but exercise PERFORMANCE did not (SMD 0.11, 95% CI -0.20 to 0.42, non-significant). Capacity is a laboratory measure; performance is what a race is.',
     '在本该最有效的 0.5 至 10 分钟区间，运动能力有改善（SMD 0.50），但运动成绩没有（SMD 0.11，95% CI -0.20 至 0.42，不显著）。能力是实验室指标，成绩才是比赛。'),
    ('The meta-analysis is routinely quoted for the flattering subgroup and never for the null one.',
     'meta 分析被反复引用其好看的亚组，而从不引用阴性的那个。'),
    ('No long-term safety data beyond a few months, and no upper limit set by any authority.',
     '没有超过数月的长期安全数据，也没有任何权威机构设定上限。'),
  ],
  refs='Saunders PMID 27797728; Trexler ISSN PMID 26175657; IOC PMID 29540367'),

I(CONSIDER, 'C', 'Dietary nitrate / beetroot', '膳食硝酸盐 / 甜菜根',
  'At least 6 mmol/d (372 mg) of nitrate, taken for more than 3 days, 2-3 hours before exercise. Read the label in mmol, not millilitres.',
  '硝酸盐至少 6 mmol/天（372 毫克），连续服用 3 天以上，运动前 2 至 3 小时。看标签要看 mmol，不是毫升。',
  'Recreationally active people rather than elite athletes, and separately anyone using it for blood pressure.',
  '休闲运动者而非精英运动员，此外还有把它用于降血压的人。',
  pros=[
    ('Time to exhaustion improves (SMD 0.33), as do total distance (0.42), muscular endurance (0.48) and peak power (0.25), across 180 primary studies and 2,672 participants.',
     '180 项原始研究、2672 名受试者的数据显示，力竭时间改善（SMD 0.33），总距离（0.42）、肌耐力（0.48）和峰值功率（0.25）同样改善。'),
    ('The blood pressure effect is more consistent than the performance effect: systolic -3.55 mmHg (-4.55 to -2.54) across 22 controlled trials.',
     '降血压效应比成绩效应更一致：22 项对照试验中收缩压降低 3.55 mmHg（-4.55 至 -2.54）。'),
    ('Non-athletes and recreationally active people benefit most, which is unusual and makes it accessible.',
     '非运动员和休闲运动者获益最大，这一点不寻常，也让它更适合普通人。'),
  ],
  cons=[
    ('Time trial performance, the one outcome that maps onto racing, is NULL. So is VO2max. The umbrella review is blunt about this.',
     '计时赛成绩，也就是唯一能对应到比赛的指标，是阴性的。最大摄氧量也是。伞式综述对此直言不讳。'),
    ('Antibacterial mouthwash abolishes the effect entirely, because the pathway depends on commensal bacteria on the tongue.',
     '抗菌漱口水会完全消除这个效应，因为该通路依赖舌面上的共生细菌。'),
    ('Ergogenic doses of 6-8 mmol exceed the EFSA and JECFA acceptable daily intake for nitrate of 3.7 mg/kg body weight per day in a single serving. That is a real regulatory tension, not a technicality.',
     '6 至 8 mmol 的增效剂量在单次服用中就超过了 EFSA 和 JECFA 对硝酸盐每日 3.7 毫克/公斤体重的可接受摄入量。这是实实在在的监管冲突，不是文字游戏。'),
    ('Additive hypotension with organic nitrates such as glyceryl trinitrate and isosorbide mononitrate, and with PDE5 inhibitors such as sildenafil and tadalafil. Care with any antihypertensive.',
     '与硝酸甘油、单硝酸异山梨酯等有机硝酸酯，以及西地那非、他达拉非等 PDE5 抑制剂有叠加的降压作用。与任何降压药合用都需谨慎。'),
  ],
  refs='Poon umbrella review PMID 40085422; Bahadoran PMID 29141968; Govoni PMID 18793740'),

I(CONSIDER, 'B', "St John's wort", '圣约翰草',
  '900 mg/d of standardised extract, usually 300 mg three times daily. Trials ran 4-12 weeks.',
  '标准化提取物 900 毫克/天，通常 300 毫克每日三次。试验周期为 4 至 12 周。',
  'Adults with mild to moderate unipolar depression who take NO other medication whatsoever and no hormonal contraception.',
  '轻中度单相抑郁的成人，且完全不服用任何其他药物，也不使用激素类避孕。',
  pros=[
    ('It genuinely works for mild to moderate depression. Cochrane pooled 29 trials and 5,489 patients: response-rate ratio 1.28 (1.10-1.49) in the 9 larger trials.',
     '它对轻中度抑郁确实有效。Cochrane 汇总 29 项试验、5489 名患者：9 项较大试验中应答率比为 1.28（1.10-1.49）。'),
    ('Side-effect burden is lower than standard antidepressants in the trials, which is the main reason patients seek it out.',
     '在试验中其副作用负担低于标准抗抑郁药，这是患者选择它的主要原因。'),
    ('In the EU it is handled as a herbal medicinal product rather than a food supplement, so product quality is better controlled than for most botanicals.',
     '在欧盟它按草药药品而非食品补充剂管理，因此产品质量控制优于多数植物类产品。'),
  ],
  cons=[
    ('This has the most dangerous interaction profile in this entire document. Hyperforin is a potent pregnane X receptor ligand and therefore a strong inducer of CYP3A4, CYP2C9, CYP1A2 and P-glycoprotein.',
     '它是本文中相互作用最危险的一个。贯叶金丝桃素是强效孕烷 X 受体配体，因而是 CYP3A4、CYP2C9、CYP1A2 和 P-糖蛋白的强诱导剂。'),
    ('Documented consequences: oral contraceptive failure with breakthrough bleeding and unintended pregnancy; loss of ciclosporin and tacrolimus levels leading to transplant rejection; antiretroviral failure with indinavir; reduced digoxin and warfarin effect; and serotonin syndrome when combined with SSRIs.',
     '已记录的后果包括：口服避孕药失效，出现突破性出血和意外妊娠；环孢素和他克莫司血药浓度下降导致移植排斥；与茚地那韦合用导致抗逆转录病毒治疗失败；地高辛和华法林效果减弱；与 SSRI 合用引发 5-羟色胺综合征。'),
    ('The efficacy estimate is unstable. The response-rate ratio was 1.28 in the 9 larger trials but 1.87 in the 9 smaller ones, and there is a strong country-of-origin effect concentrated in German-speaking countries.',
     '有效性估计并不稳定。9 项较大试验中应答率比为 1.28，9 项较小试验中却是 1.87，而且存在集中于德语国家的明显来源国效应。'),
    ('Photosensitivity, and it should be stopped before elective surgery.',
     '有光敏性，择期手术前应当停用。'),
    ('Practically speaking this is suitable for almost nobody, because almost everyone is on something.',
     '实际上它几乎不适合任何人，因为几乎每个人都在吃点什么药。'),
  ],
  refs='Cochrane Linde PMID 18843608; Nicolussi PMID 31742659; Moore PNAS DOI 10.1073/pnas.130155097'),

I(CONSIDER, 'C', 'Lactase and pancreatic enzymes', '乳糖酶与胰酶',
  'Lactase 3,000-9,000 FCC units with the first bite of dairy. Pancrelipase is prescribed in lipase units per meal and titrated.',
  '乳糖酶：随第一口乳制品服 3000 至 9000 FCC 单位。胰酶按每餐脂肪酶单位处方，并逐步调整。',
  'Adults with hydrogen-breath-test-confirmed lactose maldigestion, and patients with objectively confirmed exocrine pancreatic insufficiency.',
  '经氢呼气试验确诊乳糖消化不良的成人，以及客观确诊外分泌胰腺功能不全的患者。',
  pros=[
    ('These are real enzymes replacing real deficiencies. Pancreatic enzyme replacement raises the coefficient of fat absorption from 63.1% to 83.7% in chronic pancreatitis, which is an objective physiological measurement rather than a symptom score.',
     '这是真正的酶在替代真正的缺乏。在慢性胰腺炎中，胰酶替代把脂肪吸收系数从 63.1% 提高到 83.7%，这是客观的生理测量，而不是症状评分。'),
    ('Lactase lets people keep dairy in the diet rather than eliminating a whole food group.',
     '乳糖酶让人能继续吃乳制品，而不必整个食物类别都戒掉。'),
    ('Pancrelipase is under-prescribed rather than over-sold, which is the opposite of the pattern in this document.',
     '胰酶是被开得太少而不是卖得太多，这与本文的普遍规律正好相反。'),
  ],
  cons=[
    ('Generic digestive enzyme complexes treat a condition that does not exist. There is no recognised syndrome of generalised enzyme insufficiency in healthy adults, and the pancreas has roughly 90% functional reserve before malabsorption appears.',
     '泛泛的“复合消化酶”治的是一个并不存在的病。健康成人不存在公认的“全面酶不足”综合征，而胰腺要损失约 90% 的功能才会出现吸收不良。'),
    ('Using enzyme blends to self-treat undiagnosed persistent gut symptoms delays the diagnosis of coeliac disease, inflammatory bowel disease, pancreatic disease and colorectal cancer. That is the main harm.',
     '用复合酶自行处理未确诊的持续胃肠症状，会延误乳糜泻、炎症性肠病、胰腺疾病和结直肠癌的诊断。这才是主要危害。'),
    ('Consumer enzyme products are dosed in non-comparable proprietary activity units by design, so cross-product comparison is impossible.',
     '消费级酶产品按互不可比的专有活性单位计量，这是设计如此，因此产品之间无法比较。'),
    ('Pancrelipase is porcine-derived, which matters for observant Muslim and Jewish patients and for vegetarians, and cystic fibrosis patients must not exceed the weight-based ceiling because of fibrosing colonopathy risk.',
     '胰酶来源于猪，这对严格遵守教规的穆斯林和犹太患者以及素食者很重要；囊性纤维化患者不得超过按体重设定的上限，因为存在纤维化结肠病风险。'),
  ],
  refs='de la Iglesia-Garcia PMID 27941156; Gan PMID 29212278; de Vrese PMID 25042846; Munasinghe PMID 20204691'),

]
