# -*- coding: utf-8 -*-
"""SKIP and AVOID tiers. Same convention: no raw double-quote inside string literals."""
from supp_data import I, SKIP, AVOID

ITEMS2 = [

# ============================================================ SKIP
I(SKIP, 'A', 'Multivitamin / multimineral', '复合维生素与矿物质',
  'One tablet daily. There is no established effective dose because there is no established clinical effect in replete adults.',
  '每日一片。不存在“有效剂量”，因为在营养充足的成人中不存在已确立的临床效应。',
  'Genuine deficiency or high-probability deficiency: post-bariatric, malabsorption, strict vegans, long-term metformin users, heavy alcohol use, the housebound.',
  '确有缺乏或高度可能缺乏的人：减重手术后、吸收不良、严格纯素、长期二甲双胍使用者、大量饮酒者、久不出门者。',
  pros=[
    ('For someone with a genuine deficiency it is a cheap way to cover several nutrients at once, and that is a real use.',
     '对确实存在缺乏的人来说，这是一次覆盖多种营养素的便宜办法，这个用途是真实的。'),
    ('Doses are usually at reference-intake level, so a plain multivitamin rarely pushes any single nutrient near its upper limit on its own.',
     '其剂量通常在参考摄入量水平，所以单独吃一片普通复合维生素很少会把某一种营养素推到接近上限。'),
    ('COSMOS-Web and COSMOS-Mind reported a memory signal, which is the only positive finding in this entry and is weak.',
     'COSMOS-Web 和 COSMOS-Mind 报告了记忆方面的信号，这是本条目里唯一的阳性发现，而且很弱。'),
  ],
  cons=[
    ('It does not prevent cardiovascular disease, cancer or death. Physicians Health Study II (n=14,641, 11.2 years): major cardiovascular events HR 1.01 (0.91-1.10).',
     '它不能预防心血管病、癌症或死亡。医师健康研究 II（n=14641，11.2 年）：主要心血管事件 HR 1.01（0.91-1.10）。'),
    ('The largest dataset points the wrong way. Pooled US cohorts (n=390,124, up to 27 years, 164,762 deaths): daily multivitamin users had HIGHER all-cause mortality, HR 1.04 (1.02-1.07). This is observational and probably reflects sick people starting supplements, but it is not the direction the marketing implies.',
     '最大的数据集指向相反方向。美国多队列合并分析（n=390124，随访最长 27 年，164762 例死亡）：每日服用者全因死亡更高，HR 1.04（1.02-1.07）。这是观察性数据，很可能反映的是生病的人开始吃补充剂，但方向与营销暗示的相反。'),
    ('The USPSTF gives it an I statement, meaning the evidence is insufficient to weigh benefits against harms. The industry reports this as vindication, which it is not.',
     'USPSTF 给它的是 I 级声明，意思是证据不足以权衡利弊。行业把这当成背书来引用，而它并不是。'),
    ('The nutrient-gap argument has never converted into a clinical outcome in a healthy replete adult, and this is a roughly 8 billion US dollar per year category resting on it.',
     '“营养缺口”这个论点从未在健康且营养充足的成人中转化为临床结局，而一个每年约 80 亿美元的品类就建立在它之上。'),
    ('Vitamin K content antagonises warfarin, so switching brands or starting and stopping the product shifts INR. Treat it as a dosing variable.',
     '其中的维生素 K 会拮抗华法林，因此换品牌或开始与停用都会改变 INR。要把它当作一个剂量变量。'),
    ('Risk comes from stacking. A multivitamin plus a separate high-dose single nutrient is how people cross an upper limit without noticing.',
     '风险来自叠加。一片复合维生素再加一种单独的大剂量营养素，人们就是这样在不知不觉中越过上限的。'),
  ],
  refs='USPSTF PMID 35727271; O Connor PMID 35727272; Loftfield PMID 38922615; PHS II'),

I(SKIP, 'B', 'Collagen peptides', '胶原蛋白肽',
  '2.5-10 g/d of hydrolysed collagen for skin trials. UC-II is a different molecule dosed at about 40 mg/d and is not interchangeable.',
  '皮肤类试验用水解胶原 2.5 至 10 克/天。UC-II 是另一种分子，剂量约 40 毫克/天，两者不可互换。',
  'Nobody, on the best available analysis.', '按目前最好的分析，没有适用人群。',
  pros=[
    ('There is a weak, moderate-certainty signal for knee osteoarthritis pain: SMD -0.58 (-0.98 to -0.18) across 4 trials and 507 patients. All included trials had high risk of bias.',
     '在膝骨关节炎疼痛上有一个弱的、中等确定性的信号：4 项试验、507 名患者，SMD -0.58（-0.98 至 -0.18）。所有纳入试验偏倚风险都高。'),
    ('Safety is benign. The problem with collagen is efficacy, not harm.',
     '安全性良好。胶原的问题在于有效性，不在于危害。'),
  ],
  cons=[
    ('This is the cleanest documented case of funding bias in the supplement literature. Myung and Park pooled 23 trials and 1,474 participants. Headline: collagen improved skin hydration, elasticity and wrinkles. Subgroup analysis: studies WITHOUT pharmaceutical-company funding showed no effect on any of the three, and high-quality studies showed no effect. The effect exists only in industry-funded, lower-quality trials.',
     '这是补充剂文献中资助偏倚被记录得最干净的案例。Myung 与 Park 汇总 23 项试验、1474 名受试者。头条结论：胶原改善皮肤含水量、弹性和皱纹。亚组分析：没有药企资助的研究，这三项全都没有效应；高质量研究同样没有效应。效应只存在于行业资助的低质量试验里。'),
    ('Collagen is a poor-quality protein. It lacks tryptophan and is a poor source of essential amino acids, so it displaces better protein in the diet.',
     '胶原是低质量蛋白。它不含色氨酸，必需氨基酸来源也差，因此会挤占饮食中更好的蛋白。'),
    ('Marine collagen in fish allergy; bovine sourcing matters for religious dietary restriction and BSE-region concerns.',
     '鱼类过敏者注意海洋胶原；牛源对宗教饮食限制和疯牛病疫区来源问题也很要紧。'),
  ],
  refs='Myung & Park Am J Med 2025 PMID 40324552; Lin PMID 37717022; PMID 33742704'),

I(SKIP, 'B', 'Glucosamine and chondroitin', '氨基葡萄糖与软骨素',
  'Glucosamine 1,500 mg/d plus chondroitin 1,200 mg/d, the GAIT regimen. Form matters and is routinely ignored.',
  '氨基葡萄糖 1500 毫克/天加软骨素 1200 毫克/天，即 GAIT 方案。盐型很重要，却常被忽略。',
  'At most, people with moderate to severe knee osteoarthritis pain, on subgroup data only.',
  '最多只适用于中重度膝骨关节炎疼痛者，且仅依据亚组数据。',
  pros=[
    ('In the GAIT moderate-to-severe pain stratum the combination beat placebo, 79.2% versus 54.3% response (P=0.002). This was pre-specified but underpowered, and the authors themselves cautioned against over-reading it.',
     '在 GAIT 的中重度疼痛分层中，联用优于安慰剂，应答率 79.2% 对 54.3%（P=0.002）。该分层是预先设定的，但把握度不足，作者本人也提醒不要过度解读。'),
    ('Cochrane found a short-term chondroitin benefit: 10% absolute pain improvement, NNT 5, at low to moderate quality.',
     'Cochrane 发现软骨素有短期获益：疼痛绝对改善 10%，NNT 5，质量为低至中等。'),
    ('As safe as placebo in the trials.',
     '在试验中安全性与安慰剂相当。'),
  ],
  cons=[
    ('The definitive trial was null. GAIT was NIH-funded, n=1,583, 24 weeks, with a celecoxib active control, designed specifically to remove industry influence. Glucosamine +3.9 percentage points over placebo (P=0.30), chondroitin +5.3 (P=0.17), combination +6.5 (P=0.09). Celecoxib worked; the supplements did not.',
     '决定性试验是阴性的。GAIT 由 NIH 资助，n=1583，24 周，设塞来昔布阳性对照，专为排除行业影响而设计。氨基葡萄糖比安慰剂高 3.9 个百分点（P=0.30），软骨素高 5.3（P=0.17），联用高 6.5（P=0.09）。塞来昔布有效，补充剂无效。'),
    ('Cochrane found glucosamine benefit ONLY for the Rotta-brand crystalline glucosamine sulfate preparation. Pooled non-Rotta preparations failed to show any pain benefit. Almost nothing sold in shops is the Rotta preparation.',
     'Cochrane 发现氨基葡萄糖的获益只出现在 Rotta 品牌的结晶型硫酸氨基葡萄糖制剂上。非 Rotta 制剂合并后在疼痛上没有任何获益。而商店里卖的几乎都不是 Rotta 制剂。'),
    ('The industry sells cartilage regeneration. No trial has shown cartilage regeneration.',
     '行业卖的是“软骨再生”。没有任何试验显示过软骨再生。'),
    ('This is the best-documented supplement-anticoagulant interaction in this document: 20 FDA MedWatch reports linking glucosamine plus chondroitin to raised INR, bruising and bleeding on warfarin, plus 21 WHO database reports of raised INR.',
     '这是本文中记录最充分的补充剂与抗凝药相互作用：FDA MedWatch 有 20 份报告将氨基葡萄糖加软骨素与华法林使用者的 INR 升高、瘀伤和出血联系起来，WHO 数据库另有 21 份 INR 升高报告。'),
    ('Shellfish-derived glucosamine matters in shellfish allergy.',
     '甲壳类来源的氨基葡萄糖对甲壳类过敏者很要紧。'),
  ],
  refs='GAIT PMID 16495392; Cochrane chondroitin PMID 25629804; Cochrane glucosamine PMID 15846645'),

I(SKIP, 'D', 'NMN (nicotinamide mononucleotide)', 'NMN（烟酰胺单核苷酸）',
  '250-2,000 mg/d in trials, most commonly 250 mg/d for 12 weeks. No dose has improved a clinical outcome.',
  '试验剂量 250 至 2000 毫克/天，最常见为 250 毫克/天持续 12 周。没有任何剂量改善过临床结局。',
  'Nobody demonstrably.', '没有可证实的适用人群。',
  pros=[
    ('It reliably raises blood NAD+ two to threefold, so the pill is absorbed and metabolised as claimed.',
     '它能稳定地把血中 NAD+ 提高 2 至 3 倍，说明药片确如所称被吸收和代谢了。'),
    ('One 60-person trial in older adults with impaired physical function reported maintained walking speed and improved subjective sleep at 250 mg/d for 12 weeks. Single small trial.',
     '一项 60 人的试验在身体功能受损的老年人中报告，250 毫克/天持续 12 周可维持步速并改善主观睡眠。单项小试验。'),
  ],
  cons=[
    ('This is the purest biomarker-for-outcome substitution in the supplement market. Raising NAD+ is not a health outcome.',
     '这是补充剂市场上最纯粹的“用生物标志物冒充结局”的例子。把 NAD+ 提上去本身不是一个健康结局。'),
    ('Two independent meta-analyses found nothing. Eight randomised trials in 342 people, and separately 12 studies in 513 people: no effect on fasting glucose, fasting insulin, HbA1c, HOMA-IR or any lipid fraction.',
     '两项独立 meta 分析什么也没发现。8 项随机试验、342 人，以及另外 12 项研究、513 人：对空腹血糖、空腹胰岛素、糖化血红蛋白、HOMA-IR 及各项血脂均无效应。'),
    ('A systematic review of 10 trials in 437 people found grip strength 29.9 kg before and 30.5 kg after, with skeletal muscle mass index unchanged. Non-significant.',
     '一项纳入 10 项试验、437 人的系统综述显示握力从 29.9 公斤到 30.5 公斤，骨骼肌质量指数不变。不显著。'),
    ('No contraindications are characterised because no adequately powered safety population exists. No upper limit has been set and EFSA has not authorised it as a novel food.',
     '没有明确的禁忌，因为不存在样本量足够的安全性人群。没有设定上限，EFSA 也未批准其为新型食品。'),
    ('Avoid in pregnancy, lactation and active malignancy. NAD+ is a substrate for tumour metabolism and no oncology safety data exist.',
     '妊娠期、哺乳期和活动性恶性肿瘤者应避免。NAD+ 是肿瘤代谢的底物，且没有肿瘤学安全数据。'),
  ],
  refs='PMID 39531138; PMID 39116016; Wen PMID 39221308'),

I(SKIP, 'C', 'Nicotinamide riboside (NR)', '烟酰胺核糖（NR）',
  '250-1,000 mg/d commercially. EFSA assessed 300 mg/d as safe. Trials used up to 2,000 mg/d.',
  '市售 250 至 1000 毫克/天。EFSA 评估 300 毫克/天为安全。试验用到 2000 毫克/天。',
  'People with peripheral artery disease have the single best-supported claim, and it is thin.',
  '外周动脉疾病患者的证据是其中最好的，而这已经很薄了。',
  pros=[
    ('The NICE trial (n=90, 6 months) improved 6-minute walk distance by 17.6 m versus placebo, and by 31.0 m in those taking at least 75% of pills.',
     'NICE 试验（n=90，6 个月）使 6 分钟步行距离比安慰剂多 17.6 米，在服药依从性至少 75% 的人中多 31.0 米。'),
    ('More human trial data exist than for NMN, and EFSA has actually assessed its safety, which is more than most items here can say.',
     '它的人体试验数据比 NMN 多，而且 EFSA 确实评估过其安全性，这一点本文多数条目都做不到。'),
  ],
  cons=[
    ('More trials than NMN and a worse hit rate, which is informative. The pattern is consistent: NAD+ rises two to threefold, the clinical endpoint does not move.',
     '试验比 NMN 多，命中率反而更低，这本身很说明问题。规律是一致的：NAD+ 升高 2 至 3 倍，临床终点不动。'),
    ('Long COVID (n=58, 2,000 mg/d, 20 weeks): NAD+ up 2.6 to 3.1-fold, no significant improvement in cognition, fatigue, sleep or mood.',
     '长新冠（n=58，2000 毫克/天，20 周）：NAD+ 升高 2.6 至 3.1 倍，认知、疲劳、睡眠、情绪均无显著改善。'),
    ('Obese insulin-resistant men (n=40, 2,000 mg/d, 12 weeks): insulin sensitivity, endogenous glucose production, glucose disposal and oxidation were all unimproved, in the authors own words.',
     '肥胖胰岛素抵抗男性（n=40，2000 毫克/天，12 周）：用作者原话，胰岛素敏感性、内源性葡萄糖生成、葡萄糖处置与氧化全部未改善。'),
    ('Mild cognitive impairment trials at 1,000 mg/d were null.',
     '1000 毫克/天治疗轻度认知障碍的试验为阴性。'),
    ('EFSA caps pregnancy and lactation at 230 mg/d. Sum total nicotinamide exposure if also taking prescription niacin. As with NMN, no oncology safety data exist.',
     'EFSA 把妊娠期和哺乳期上限定在 230 毫克/天。若同时服用处方烟酸，需合计烟酰胺总暴露量。与 NMN 一样，没有肿瘤学安全数据。'),
  ],
  refs='Wu PMID 41357333; Dollerup PMID 29992272; McDermott NICE PMID 38871717; Orr PMID 37994989'),

I(SKIP, 'D', 'Resveratrol', '白藜芦醇',
  'Trials span 150 mg/d to gram doses. The EU caps synthetic trans-resveratrol at 150 mg/d in supplements, adults only.',
  '试验剂量从 150 毫克/天到克级。欧盟把合成反式白藜芦醇在补充剂中的上限定为 150 毫克/天，且仅限成人。',
  'Possibly people who already have type 2 diabetes. The healthy-ageing consumer is in the null subgroup.',
  '可能适用于已患 2 型糖尿病的人。以“健康抗老”为目的的消费者正处在无效的那个亚组里。',
  pros=[
    ('An 11-trial meta-analysis found significant improvement in glucose control and insulin sensitivity in people who already had diabetes, and explicitly no effect in non-diabetic people.',
     '一项 11 项试验的 meta 分析发现，在已患糖尿病的人中血糖控制和胰岛素敏感性显著改善，并明确指出在非糖尿病者中无效应。'),
  ],
  cons=[
    ('It is the cautionary tale the rest of this category has not learned from. Sirtris was acquired by GSK for 720 million US dollars and the development programme was discontinued.',
     '它是这个品类其余成员没有从中学到教训的警示故事。Sirtris 被 GSK 以 7.2 亿美元收购，随后开发项目终止。'),
    ('The best-designed human trial was null: 150 mg/d for 6 months in overweight adults, no effect on insulin sensitivity (adjusted Matsuda index 5.18 versus 5.50 on placebo).',
     '设计最好的人体试验是阴性的：超重成人服用 150 毫克/天共 6 个月，对胰岛素敏感性无效（校正 Matsuda 指数 5.18，安慰剂 5.50）。'),
    ('It can make exercise worse. In aged men undergoing training, resveratrol BLUNTED the training-induced cardiovascular improvements, the opposite of the marketed exercise-mimetic claim.',
     '它可能让运动效果变差。在接受训练的老年男性中，白藜芦醇削弱了训练带来的心血管改善，与其宣传的“运动模拟剂”正好相反。'),
    ('Antiplatelet activity, so care with warfarin and antiplatelets. Oestrogen-sensitive conditions warrant caution. Gram doses cause gastrointestinal intolerance, and the oncology programme saw renal adverse events.',
     '有抗血小板活性，与华法林和抗血小板药合用需谨慎。雌激素敏感性疾病也需谨慎。克级剂量引起胃肠不耐受，肿瘤学项目中还出现过肾脏不良事件。'),
  ],
  refs='de Ligt PMID 32492138; Liu PMID 24695890; Gliemann J Physiol; EU Decision 2016/1190'),

I(SKIP, 'D', 'Spermidine', '亚精胺',
  '0.9 mg/d was the dose in the definitive trial. Commercial products supply roughly 1-6 mg/d.',
  '决定性试验用的是 0.9 毫克/天。市售产品约提供 1 至 6 毫克/天。',
  'Nobody demonstrably.', '没有可证实的适用人群。',
  pros=[
    ('The autophagy mechanism is genuine in yeast, flies, worms and mice, and lifespan is extended in those organisms.',
     '自噬机制在酵母、果蝇、线虫和小鼠中是真实的，这些生物的寿命确实被延长了。'),
  ],
  cons=[
    ('The one well-conducted human test failed in exactly the target population. SmartAge was 12 months, double-masked, placebo-controlled, in 100 adults aged 60-90 with subjective cognitive decline. Primary outcome difference -0.03 (95% CI -0.11 to 0.05), P=0.47, against a pre-registered primary endpoint.',
     '唯一一项做得规范的人体试验，在完全对口的目标人群中失败了。SmartAge 为 12 个月、双盲、安慰剂对照，纳入 100 名 60 至 90 岁有主观认知下降的成人。针对预先注册的主要终点，组间差异为 -0.03（95% CI -0.11 至 0.05），P=0.47。'),
    ('The observational case rests on dietary intake epidemiology, and spermidine-rich foods are wheat germ, legumes, mushrooms and aged cheese. That is a dietary pattern, not a molecule.',
     '观察性依据来自膳食摄入流行病学，而富含亚精胺的食物是麦胚、豆类、蘑菇和陈年奶酪。那是一种饮食模式，不是一个分子。'),
    ('Dietary intake from food is typically several-fold higher than most supplements provide, which by itself undermines the supplement premise.',
     '从食物中摄入的量通常比多数补充剂提供的高出数倍，这一点本身就削弱了补充剂存在的前提。'),
    ('Wheat-germ-derived products are unsuitable in coeliac disease and wheat allergy. Polyamines are growth-supporting and elevated in many tumours, and polyamine depletion is an active oncology strategy, so avoid during active malignancy.',
     '麦胚来源的产品不适合乳糜泻和小麦过敏者。多胺具有促生长作用，在许多肿瘤中升高，而多胺耗竭正是当前肿瘤治疗的一种策略，因此活动性恶性肿瘤期间应避免。'),
  ],
  refs='SmartAge PMID 35616942; protocol PMID 31039826'),

I(SKIP, 'C', 'Curcumin / turmeric extract', '姜黄素 / 姜黄提取物',
  'About 1,000 mg/d of curcuminoids in the knee osteoarthritis trials. Culinary turmeric is a different exposure entirely.',
  '膝骨关节炎试验中约为姜黄素类 1000 毫克/天。烹饪用姜黄的暴露量完全是另一回事。',
  'At most, people with symptomatic knee osteoarthritis, if the meta-analytic signal survives the bias problem.',
  '最多适用于有症状的膝骨关节炎患者，前提是那个 meta 分析信号能扛过偏倚问题。',
  pros=[
    ('A Bayesian network meta-analysis of 23 studies and 2,175 knee osteoarthritis patients found pain on a visual analogue scale -1.63 (-2.91 to -0.45) and total WOMAC -18.85.',
     '一项贝叶斯网络 meta 分析纳入 23 项研究、2175 名膝骨关节炎患者，视觉模拟疼痛评分为 -1.63（-2.91 至 -0.45），WOMAC 总分为 -18.85。'),
    ('Culinary use in food is entirely reasonable and carries no established risk.',
     '作为食物调味完全合理，没有已确立的风险。'),
  ],
  cons=[
    ('It was classified in the Journal of Medicinal Chemistry as both a PAINS (pan-assay interference compound) and an invalid metabolic panacea: an unstable, reactive, nonbioavailable compound and therefore a highly improbable lead. That is a formal medicinal-chemistry verdict, not an opinion.',
     '《药物化学杂志》把它同时归类为 PAINS（泛测定干扰化合物）和“无效的代谢万灵药”：一个不稳定、易反应、生物利用度极低的化合物，因此几乎不可能成为先导物。这是药物化学领域的正式判定，不是个人看法。'),
    ('The dose on the label is disconnected from systemic exposure. Unconjugated plasma curcumin stays below 2 nM even at high dose with piperine, against the 1-100 micromolar concentrations used in the in-vitro work that generated the claims. Adding piperine does not raise unconjugated plasma curcumin.',
     '标签上的剂量与体内暴露量脱钩。即便高剂量并加胡椒碱，血浆游离姜黄素仍低于 2 nM，而产生这些说法的体外实验用的是 1 至 100 微摩尔。加胡椒碱并不能提高血浆游离姜黄素。'),
    ('The osteoarthritis trials are mostly industry-funded with high heterogeneity.',
     '骨关节炎试验多为行业资助，异质性高。'),
    ('Turmeric is the most commonly used of the six botanicals linked to liver injury in US survey data (236 of 9,685 respondents), and 10 DILIN cases published in 2023 included five hospitalisations and one death from acute liver failure. Seven of ten carried HLA-B*35:01.',
     '在美国调查数据中，姜黄是六种与肝损伤相关的植物里使用最多的一种（9685 名受访者中有 236 人），2023 年发表的 10 例 DILIN 病例中有 5 例住院、1 例死于急性肝衰竭。10 人中有 7 人携带 HLA-B*35:01。'),
    ('Antiplatelet activity raises bleeding risk with warfarin and antiplatelets. Piperine inhibits CYP3A4 broadly, so herb-drug interaction risk with cytotoxics and targeted agents is real.',
     '抗血小板活性会增加与华法林和抗血小板药合用时的出血风险。胡椒碱广泛抑制 CYP3A4，因此与细胞毒药物和靶向药之间的相互作用风险是真实的。'),
  ],
  refs='Nelson J Med Chem 2017 PMID 28074653; iScience 2025 PMC12144411; Zhao PMID 38036015; Halegoua-DeMarzio PMID 36252717; Likhitsup PMID 39102266'),

I(SKIP, 'D', 'MSM (methylsulfonylmethane)', 'MSM（二甲基砜）',
  'Trials used 2 g/d (the 2023 trial) up to 6 g/d (the 2006 pilot). No effective dose is established.',
  '试验用量从 2 克/天（2023 年试验）到 6 克/天（2006 年预试验）。没有确立的有效剂量。',
  'No population has a defensible claim.', '没有任何人群有站得住的理由。',
  pros=[
    ('A single 88-person trial reported a significant between-group difference in a knee quality-of-life composite score at 12 weeks.',
     '一项 88 人的试验报告，12 周时膝关节生活质量综合评分的组间差异显著。'),
    ('Very low toxicity signal at the doses used.',
     '在所用剂量下毒性信号极低。'),
  ],
  cons=[
    ('The meta-analysis found 3 randomised trials and 326 patients, of which only ONE studied MSM at all. The other two studied DMSO. Reported pain reduction was a non-significant 6.34 mm on a visual analogue scale.',
     'meta 分析共找到 3 项随机试验、326 名患者，其中只有一项真正研究了 MSM，另外两项研究的是 DMSO。报告的疼痛下降为视觉模拟评分 6.34 毫米，不显著。'),
    ('The 2008 systematic review covering 6 studies and 681 osteoarthritis patients found only 52 had ever received MSM in a controlled trial. That is the entire human evidence base.',
     '2008 年那篇系统综述涵盖 6 项研究、681 名骨关节炎患者，其中只有 52 人曾在对照试验中接受过 MSM。这就是全部的人体证据基础。'),
    ('It is present in a large share of joint supplements, which inflates the price of combination products for no measured benefit.',
     '它出现在相当大比例的关节类产品中，抬高了复方产品的价格，却没有可测量的收益。'),
    ('No characterised drug interactions, largely because almost nobody has looked. No pregnancy or lactation data.',
     '没有明确的药物相互作用，主要是因为几乎没有人研究过。没有妊娠和哺乳期数据。'),
  ],
  refs='Brien PMID 19474240; Brien PMID 18417375; Toguchi PMID 37447322'),

I(SKIP, 'D', 'Astaxanthin', '虾青素',
  '4-12 mg/d in skin trials. EFSA acceptable daily intake is 0.2 mg/kg body weight, so 14 mg/d for a 70 kg adult.',
  '皮肤类试验为 4 至 12 毫克/天。EFSA 的每日允许摄入量为 0.2 毫克/公斤体重，70 公斤成人即 14 毫克/天。',
  'Nobody with a demonstrated clinical outcome.', '没有任何人群有已证实的临床结局获益。',
  pros=[
    ('Small improvements in skin moisture (ES 0.53) and elasticity (ES 0.77) across 9 oral randomised trials.',
     '9 项口服随机试验显示皮肤含水量（ES 0.53）和弹性（ES 0.77）有小幅改善。'),
    ('One oxidative-stress marker, advanced oxidation protein products, fell significantly after exercise.',
     '一个氧化应激指标，即晚期氧化蛋白产物，在运动后显著下降。'),
  ],
  cons=[
    ('The core selling point is a test-tube potency ratio, often quoted as 1,000 times coenzyme Q10 at quenching singlet oxygen. That is an in-vitro number with no demonstrated clinical consequence, and it is exactly the kind of assay-derived claim the PAINS critique warns about.',
     '它的核心卖点是一个试管里的效力倍数，常被引用为“淬灭单线态氧的能力是辅酶 Q10 的 1000 倍”。那是一个体外数字，没有证明出任何临床后果，而这正是 PAINS 批评所警告的那类由测定衍生出来的说法。'),
    ('Wrinkle depth, the outcome consumers actually buy it for, was NOT significant (-0.26, 95% CI -0.58 to 0.06).',
     '皱纹深度，也就是消费者真正为之买单的指标，并不显著（-0.26，95% CI -0.58 至 0.06）。'),
    ('In exercise trials MDA, TBARS, superoxide dismutase, sulfhydryls, creatine kinase and IL-6 were all non-significant, directly contradicting the antioxidant marketing.',
     '在运动试验中，MDA、TBARS、超氧化物歧化酶、巯基、肌酸激酶和 IL-6 全部不显著，与其抗氧化营销直接冲突。'),
    ('EFSA noted that children exceed the acceptable daily intake with 8 mg/d supplements, so the common commercial 12 mg dose exceeds the safe intake for a 40 kg adolescent.',
     'EFSA 指出，8 毫克/天的补充剂就会让儿童超过每日允许摄入量，因此常见的 12 毫克商业剂量已超过 40 公斤青少年的安全摄入水平。'),
    ('Krill-derived astaxanthin in shellfish allergy. Reported 5-alpha-reductase inhibition is poorly characterised and matters in hormone-sensitive conditions.',
     '甲壳类过敏者注意磷虾来源的虾青素。有报告称其抑制 5α-还原酶，特性不明，对激素敏感性疾病有影响。'),
  ],
  refs='Zhou PMID 34578794; Ma PMID 35091276; You PMID 41710469; EFSA PMID 32874213'),

I(SKIP, 'D', 'HMB', 'HMB（β-羟基-β-甲基丁酸）',
  '3 g/d, usually as three 1 g doses. No dose or duration rescues the result in trained people.',
  '3 克/天，通常分三次每次 1 克。在训练有素者身上，任何剂量或时长都救不回这个结果。',
  'On the balance of umbrella reviews, at most untrained beginners or clinically muscle-wasting populations.',
  '综合伞式综述来看，最多适用于未受训练的初学者，或有临床肌肉消耗的人群。',
  pros=[
    ('An umbrella review of 11 studies and 41 datasets found small but significant pooled effects on muscle mass (ES 0.21), muscle strength index (0.27) and fat-free mass (0.22).',
     '一项涵盖 11 项研究、41 个数据集的伞式综述发现，肌肉质量（ES 0.21）、肌力指数（0.27）和去脂体重（0.22）有小但显著的合并效应。'),
    ('No established contraindication, no drug interaction and not a doping risk.',
     '没有已确立的禁忌，没有药物相互作用，也不构成兴奋剂风险。'),
  ],
  cons=[
    ('In trained and competitive athletes it is a flat null across every endpoint. Six randomised trials, n=193: bench press effect size 0.00, leg press 0.09, body mass -0.01, fat-free mass 0.16, fat mass -0.20, all non-significant and described by the authors as trivial. Results were unchanged by dose, duration, training level or dietary co-intervention.',
     '在训练有素和竞技运动员中，所有终点上都是彻底的阴性。6 项随机试验，n=193：卧推效应量 0.00，腿举 0.09，体重 -0.01，去脂体重 0.16，脂肪量 -0.20，全部不显著，作者形容为微不足道。剂量、时长、训练水平或饮食联合干预都不改变结果。'),
    ('An umbrella review of 15 systematic reviews found only 5 favoured HMB for lean soft-tissue mass; 10 reported no difference or insufficient evidence.',
     '一项涵盖 15 篇系统综述的伞式综述发现，只有 5 篇支持 HMB 对瘦软组织质量有益，10 篇报告无差异或证据不足。'),
    ('Its reputation was built on a handful of early trials from a small number of affiliated laboratories and never replicated independently in trained athletes.',
     '它的声誉建立在少数几家关联实验室的早期试验之上，从未在训练有素的运动员中被独立重复。'),
    ('One of the more expensive ingredients per gram, so it displaces spend from protein and creatine, which work.',
     '按克计是较贵的成分之一，因此挤占了本可用于蛋白和肌酸这两样真正有效东西的预算。'),
  ],
  refs='Sanchez-Martinez PMID 29249685; Phillips PMID 35818771; Bideshki PMID 39797501'),

I(SKIP, 'A', 'Ginkgo biloba', '银杏叶',
  '240 mg/d of EGb 761, which is the dose that failed in both prevention trials.',
  'EGb 761 240 毫克/天，这正是两项预防试验中失败的剂量。',
  'Nobody, for preventing dementia. Possibly people with established dementia, on low-certainty evidence.',
  '在预防痴呆上没有适用人群。可能适用于已确诊痴呆者，但证据确定性低。',
  pros=[
    ('The 2026 Cochrane review of 82 studies and 10,613 participants found uncertain benefit for global clinical status at 6 months in people with cognitive complaints, at low certainty.',
     '2026 年 Cochrane 综述纳入 82 项研究、10613 名受试者，发现有认知主诉者在 6 个月时整体临床状态可能获益，确定性为低。'),
    ('Unusually good long-term human safety data for a botanical: 240 mg/d for about 6 years in GEM without a safety signal.',
     '对一款植物类产品而言，长期人体安全数据异常充分：GEM 试验中 240 毫克/天用了约 6 年，未见安全信号。'),
  ],
  cons=[
    ('It is the strongest example in this document of a product that survived its own definitive trials. GEM randomised 3,069 older adults to 240 mg/d for a median 6.1 years: all-cause dementia HR 1.12 (0.94-1.33), Alzheimer disease HR 1.16 (0.97-1.39). The point estimates are above 1.',
     '它是本文中“在自己的决定性试验之后依然活着”的最强例子。GEM 把 3069 名老年人随机到 240 毫克/天，中位随访 6.1 年：全因痴呆 HR 1.12（0.94-1.33），阿尔茨海默病 HR 1.16（0.97-1.39）。点估计值都在 1 以上。'),
    ('GuidAge replicated the null in 2,854 adults over 5 years.',
     'GuidAge 在 2854 名成人中随访 5 年，重复了这个阴性结果。'),
    ('The bleeding question is genuinely contested rather than settled. A meta-analysis of 18 trials in 1,985 adults found no significant effect on platelet aggregation or coagulation parameters, but case reports of bleeding exist and stopping before elective surgery is prudent.',
     '出血的问题确实存在争议，而非已有定论。一项 18 项试验、1985 名成人的 meta 分析未发现对血小板聚集或凝血指标有显著影响，但出血的个案报告确实存在，择期手术前停用是稳妥做法。'),
    ('Only standardised extracts have any data behind them. Unstandardised leaf products have none.',
     '只有标准化提取物背后有数据。非标准化的叶类产品没有任何数据。'),
  ],
  refs='GEM DeKosky PMID 19017911; GuidAge Vellas PMID 22959217; Cochrane Wieland PMID 41641880'),

I(SKIP, 'D', 'Valerian', '缬草',
  'Roughly 300-600 mg of extract 30-120 minutes before bed. No effective dose is established.',
  '睡前 30 至 120 分钟服提取物约 300 至 600 毫克。没有确立的有效剂量。',
  'On present evidence, nobody reliably.', '按现有证据，没有可靠的适用人群。',
  pros=[
    ('The umbrella review characterises it as having a good safety profile, which is the strongest positive statement the evidence supports.',
     '伞式综述认为它安全性良好，这是现有证据能支持的最积极的说法。'),
    ('The 2006 review found a statistically significant benefit on a dichotomous improved-sleep outcome, relative risk 1.8 (1.2-2.9).',
     '2006 年那篇综述在“睡眠改善”这个二分类结局上发现统计学显著获益，相对风险 1.8（1.2-2.9）。'),
  ],
  cons=[
    ('The 2006 authors reported publication bias, considerable heterogeneity and variable preparations in the same paper that produced the positive number. The positive number does not survive its own caveats.',
     '2006 年的作者在得出那个阳性数字的同一篇论文里，报告了发表偏倚、相当大的异质性和制剂不一致。那个阳性数字扛不住它自己的限定条件。'),
    ('The 2024 umbrella review of 8 systematic reviews concluded there is NO evidence of efficacy for the treatment of insomnia, with subjective improvements not corroborated by objective measures.',
     '2024 年那篇涵盖 8 篇系统综述的伞式综述结论是：没有证据表明它对失眠有效，主观改善没有被客观指标印证。'),
    ('The AASM guideline suggests clinicians NOT use valerian for sleep-onset or sleep-maintenance insomnia.',
     '美国睡眠医学会指南建议临床不要用缬草治疗入睡困难或睡眠维持障碍。'),
    ('Additive sedation with benzodiazepines, Z-drugs, barbiturates, opioids, antihistamines and alcohol. Case reports of hepatotoxicity exist, mostly with multi-herb combination products.',
     '与苯二氮类、Z 类药物、巴比妥类、阿片类、抗组胺药和酒精有叠加的镇静作用。有肝毒性个案报告，多见于多草药复方产品。'),
  ],
  refs='Valente umbrella review PMID 38359657; Bent PMID 17145239; Sateia AASM PMID 27998379'),

I(SKIP, 'D', 'Rhodiola rosea', '红景天',
  'Commercial convention is 200-600 mg/d of extract standardised to about 3% rosavins. There is no evidence-based dose.',
  '市售惯例是标准化至约 3% 红景天苷的提取物 200 至 600 毫克/天。不存在基于证据的剂量。',
  'Possibly people with subjective mental fatigue, on evidence too weak to justify confidence.',
  '可能适用于有主观精神疲劳的人，但证据弱到不足以让人有信心。',
  pros=[
    ('Three of five randomised trials on mental fatigue were positive, so there is a signal, however unreliable.',
     '五项关于精神疲劳的随机试验中有三项阳性，所以存在信号，尽管不可靠。'),
  ],
  cons=[
    ('The systematic review screened 206 articles, included 11 trials, and found that ALL of them exhibit either a high risk of bias or reporting flaws that hinder assessment of their true effect. No two studies reported the same outcome, so meta-analysis was impossible.',
     '那篇系统综述筛查了 206 篇文章，纳入 11 项试验，发现全部试验都存在高偏倚风险，或存在妨碍评估其真实效应的报告缺陷。没有任何两项研究报告了相同的结局，因此无法做 meta 分析。'),
    ('Only 2 of 6 physical-fatigue trials were positive.',
     '六项体力疲劳试验中只有两项阳性。'),
    ('The premium adaptogen positioning has essentially no regulatory-grade support. EFSA has authorised no health claim.',
     '高价的“适应原”定位基本没有监管级别的支持。EFSA 没有批准任何健康声称。'),
    ('No upper limit can be stated because dose-ranging and toxicity data do not exist. Theoretical additive serotonergic effects with SSRIs, SNRIs and MAOIs, and activation risk in bipolar disorder.',
     '无法给出上限，因为剂量探索和毒性数据都不存在。理论上与 SSRI、SNRI 和 MAOI 有叠加的 5-羟色胺效应，双相障碍者有躁狂激活风险。'),
  ],
  refs='Ishaque BMC Complement Altern Med PMID 22643043'),

I(SKIP, 'C', "Lion's mane (Hericium erinaceus)", '猴头菇',
  '3,000 mg/d of dried fruiting body for 16 weeks in the pivotal trial. Fruiting body and mycelium contain different compounds and are not interchangeable.',
  '关键试验为干燥子实体 3000 毫克/天、持续 16 周。子实体与菌丝体所含成分不同，不可互换。',
  'Possibly older adults with mild cognitive impairment, on the basis of a single 30-person trial.',
  '可能适用于轻度认知障碍的老年人，依据是一项 30 人的试验。',
  pros=[
    ('It is a food mushroom with a long history of dietary use, so the baseline safety expectation is reasonable.',
     '它是一种食用菌，有长期的食用历史，因此对其基础安全性的预期是合理的。'),
    ('In the pivotal trial, dementia screening scores improved at weeks 8, 12 and 16.',
     '在关键试验中，痴呆筛查评分在第 8、12 和 16 周有所改善。'),
  ],
  cons=[
    ('The pivotal trial randomised 30 Japanese adults, 15 per arm, to a dementia SCREENING scale. Scores then fell significantly 4 weeks after stopping. There is no meta-analysis and no trial with a hard endpoint.',
     '关键试验把 30 名日本成人随机分为每组 15 人，用的是痴呆筛查量表。停药 4 周后评分显著回落。没有 meta 分析，也没有任何硬终点试验。'),
    ('The only other cited trial is explicitly self-described as a pilot.',
     '另一项被引用的试验，作者自己明确称之为预试验。'),
    ('This is one of the largest gaps between marketing volume and evidence volume in the entire document. The neurogenesis claim rests on in-vitro nerve growth factor stimulation.',
     '这是全文中营销声量与证据体量差距最大的条目之一。所谓“促进神经再生”建立在体外刺激神经生长因子的基础上。'),
    ('Most retail products do not disclose whether they contain fruiting body or mycelium, so you cannot match the product to the trial.',
     '多数零售产品不披露所用是子实体还是菌丝体，因此你无法把手上的产品对应到试验里。'),
    ('Mushroom allergy is a real contraindication. Theoretical antiplatelet effects are uncharacterised in humans.',
     '蘑菇过敏是真实的禁忌。理论上的抗血小板作用在人体中未被表征。'),
  ],
  refs='Mori PMID 18844328; Li PMID 32581767'),

I(SKIP, 'C', 'Bacopa monnieri', '假马齿苋（婆罗米）',
  '300-320 mg/d of extract standardised to 50-55% bacosides, for at least 12 weeks. It is not an acute agent.',
  '标准化至 50 至 55% 假马齿苋皂苷的提取物 300 至 320 毫克/天，至少 12 周。它不是急性起效的东西。',
  'Healthy adults willing to take it daily for 12 weeks for a modest change in processing speed.',
  '愿意连续服用 12 周、以换取加工速度小幅变化的健康成人。',
  pros=[
    ('The meta-analysis restricted inclusion to chronic dosing of 12 weeks or more, which is methodologically sound, and found two statistically significant results.',
     'meta 分析把纳入范围限定为 12 周以上的长期给药，方法上是站得住的，并得到两个统计学显著的结果。'),
  ],
  cons=[
    ('Read the actual endpoints. The two significant results across 9 trials and 437 analysable subjects were a Trail Making Test B change of -17.9 MILLISECONDS and a choice reaction time change of about 10 ms. Millisecond-scale processing speed is being sold as memory and learning.',
     '要看真正的终点。9 项试验、437 名可分析受试者中，两个显著结果分别是连线测验 B 型缩短 17.9 毫秒，以及选择反应时缩短约 10 毫秒。毫秒级的加工速度变化，被当作记忆力和学习能力在卖。'),
    ('The meta-analysis authors explicitly said larger comparative trials are needed before any recommendation.',
     'meta 分析作者明确表示，在提出任何建议之前需要更大规模的对照试验。'),
    ('Nothing supports a memory or dementia effect.',
     '没有任何证据支持它对记忆或痴呆有作用。'),
    ('Gastrointestinal adverse effects (nausea, cramping, increased stool frequency) are the commonest problem. Cholinergic activity means caution with donepezil, rivastigmine and galantamine, and with anticholinergics. Animal work suggests thyroid hormone effects, so care with levothyroxine.',
     '胃肠道不良反应（恶心、腹部绞痛、排便次数增多）是最常见的问题。它具胆碱能活性，与多奈哌齐、利伐斯的明、加兰他敏以及抗胆碱药合用需谨慎。动物研究提示其影响甲状腺激素，因此与左甲状腺素合用需注意。'),
  ],
  refs='Kongkeaw PMID 24252493'),

I(SKIP, 'C', '5-HTP', '5-羟色氨酸',
  '50-300 mg/d commercially. No authoritative dose exists because no usable trial established one.',
  '市售 50 至 300 毫克/天。不存在权威剂量，因为没有可用的试验确立过。',
  'No group can be identified with confidence.', '无法有把握地指出任何适用人群。',
  pros=[
    ('The Cochrane meta-analysis produced a Peto odds ratio of 4.10 (1.28-13.15) with an NNT of 2.78, which sounds spectacular.',
     'Cochrane 的 meta 分析得出 Peto 比值比 4.10（1.28-13.15），NNT 为 2.78，听起来相当惊人。'),
  ],
  cons=[
    ('That number comes from 64 patients in 2 trials out of 108 located. Cochrane located 108 trials and could use two. The confidence interval spans a tenfold range and the authors refused to stand behind it, concluding that because effective and safe alternative antidepressants exist, the clinical usefulness of 5-HTP and tryptophan is limited at present.',
     '那个数字来自 108 项检索到的试验中的 2 项、共 64 名患者。Cochrane 找到 108 项试验，只能用两项。置信区间跨越十倍，作者拒绝为其背书，结论是：既然已有有效且安全的替代抗抑郁药，5-HTP 和色氨酸目前的临床价值有限。'),
    ('The eosinophilia-myalgia syndrome question is unresolved. The 1989 outbreak was linked to contaminated L-tryptophan and Cochrane flagged that the possibility of a similar contaminant in 5-HTP products has not been excluded.',
     '嗜酸性粒细胞增多-肌痛综合征的问题至今未解决。1989 年的疫情与污染的 L-色氨酸有关，Cochrane 指出，5-HTP 产品中存在类似污染物的可能性尚未被排除。'),
    ('Serotonin syndrome risk with SSRIs, SNRIs, MAOIs including the irreversible ones, tricyclics, tramadol, triptans, linezolid, lithium and dextromethorphan. This is a direct serotonin precursor, so the risk is mechanistic rather than theoretical.',
     '与 SSRI、SNRI、包括不可逆型在内的 MAOI、三环类、曲马多、曲普坦类、利奈唑胺、锂盐和右美沙芬合用有 5-羟色胺综合征风险。它是直接的 5-羟色胺前体，所以这个风险是机制性的，不是理论上的。'),
  ],
  refs='Cochrane Shaw PMID 11687048'),

I(SKIP, 'C', 'Vitamin K2 (MK-7 and MK-4)', '维生素 K2（MK-7 与 MK-4）',
  'MK-7 180-720 µg/d in trials. MK-4 45 mg/d in the Japanese fracture trial, roughly 250 times the MK-7 dose.',
  '试验中 MK-7 为 180 至 720 微克/天。日本骨折试验中 MK-4 为 45 毫克/天，约为 MK-7 剂量的 250 倍。',
  'Nobody with solid evidence of clinical benefit.', '没有任何人群有确凿的临床获益证据。',
  pros=[
    ('The carboxylation mechanism is real: MK-7 does carboxylate osteocalcin and matrix Gla protein, and the biomarkers move.',
     '羧化机制是真实的：MK-7 确实会羧化骨钙素和基质 Gla 蛋白，生物标志物也确实变化。'),
    ('Knapen 2013 (n=244 healthy postmenopausal women, 180 µg/d for 3 years) significantly slowed the age-related decline in bone mineral content and density at lumbar spine and femoral neck. Surrogate endpoint, and not at the total hip.',
     'Knapen 2013（244 名健康绝经后女性，180 微克/天服 3 年）显著减缓了腰椎和股骨颈骨矿含量与骨密度的随龄下降。这是替代终点，且全髋部位没有效果。'),
    ('No adverse effect level has been identified, so no upper limit exists.',
     '未发现不良作用水平，因此没有设定上限。'),
  ],
  cons=[
    ('The core sales pitch, that D3 without K2 calcifies your arteries, is a marketing construct. No randomised trial has ever shown that vitamin D supplementation causes vascular calcification which K2 then prevents.',
     '核心卖点，也就是“只补 D3 不补 K2 会让血管钙化”，是一个营销构造。没有任何随机试验显示过维生素 D 补充会导致血管钙化、而 K2 能加以阻止。'),
    ('The calcification claim has been tested and failed twice. AVADEC: 720 µg MK-7 plus vitamin D for 24 months in 365 men with aortic valve calcification, progression 275 versus 292 AU, no difference. VitaK-CAC: 360 µg MK-7 for 2 years in 167 coronary patients, coronary calcium rose from 135 to 184 AU on MK-7 anyway.',
     '钙化方面的说法已被检验两次并失败。AVADEC：365 名主动脉瓣钙化男性服用 720 微克 MK-7 加维生素 D 共 24 个月，进展为 275 对 292 AU，无差异。VitaK-CAC：167 名冠心病患者服用 360 微克 MK-7 共 2 年，MK-7 组冠脉钙化照样从 135 升到 184 AU。'),
    ('MK-4 is worse. The impressive vertebral-fracture odds ratios in K2 marketing trace to small Japanese menatetrenone trials, and when the hypothesis was tested properly the OF study (n=4,378, 45 mg/d, 36-48 months) was NULL on new vertebral fractures. One frequently cited supporting paper has been RETRACTED for research misconduct.',
     'MK-4 更糟。K2 营销中那些漂亮的椎体骨折比值比源自小型日本甲基萘醌试验，而当这个假说被正规检验时，OF 研究（n=4378，45 毫克/天，36 至 48 个月）在新发椎体骨折上是阴性的。一篇常被引用的支持性论文已因科研不端被撤稿。'),
    ('MK-4 has essentially no oral bioavailability at supplement doses. A single 420 µg dose of MK-4 was not detectable in the serum of any subject at any time point, while the same dose of MK-7 peaked at 6 hours and stayed detectable for 48 hours.',
     '在补充剂剂量下 MK-4 基本没有口服生物利用度。单次 420 微克 MK-4 在任何受试者的任何时间点都检测不到，而同剂量的 MK-7 在 6 小时达峰并可检测 48 小时。'),
    ('Absolute practical contraindication with warfarin and other vitamin K antagonists. MK-7 has a long half-life, so even modest doses destabilise INR for days to weeks.',
     '与华法林及其他维生素 K 拮抗剂在实际使用中属绝对禁忌。MK-7 半衰期长，即便中等剂量也会让 INR 在数天到数周内不稳定。'),
  ],
  refs='AVADEC Diederichsen PMID 35465686; VitaK-CAC JAMA Cardiol 2026; Knapen PMID 23525894; OF study Inoue PMID 19082528; Sato PK PMID 23140417; retracted PMID 21778673'),

I(SKIP, 'B', 'Generic multi-strain probiotic blends', '泛泛的复合菌株益生菌',
  'Marketed as 50 billion CFU and similar. The dose threshold that matters is at least 5 billion CFU/d, but only for the two specific indications.',
  '常以“500 亿 CFU”之类标示。真正有意义的剂量门槛是至少 50 亿 CFU/天，但只对那两个特定适应证有效。',
  'See the strain-specific entry in the Consider tier. A blend with no strain designators has nothing behind it.',
  '见“可以考虑”一档中的菌株特异性条目。不标菌株编号的复方产品背后没有任何依据。',
  pros=[
    ('If a blend happens to contain a strain with evidence at an adequate dose, it will work for that indication. The problem is you cannot tell from the label.',
     '如果某款复方恰好含有一种有证据的菌株且剂量足够，它对那个适应证会有效。问题是你从标签上看不出来。'),
  ],
  cons=[
    ('The category claim is unfalsifiable marketing. Probiotic describes a delivery concept, not an active ingredient. NCCIH states the point plainly: if one Lactobacillus helps prevent an illness, that does not necessarily mean another kind of Lactobacillus will.',
     '品类式声称是无法证伪的营销话术。“益生菌”描述的是一种投递概念，不是一种活性成分。NCCIH 说得很直白：如果某种乳杆菌有助于预防某种疾病，这并不必然意味着另一种乳杆菌也能。'),
    ('Disaggregate 82 randomised trials and 10,332 irritable bowel syndrome patients by strain, and GRADE certainty collapses to low or very low almost everywhere. Only 24 of the 82 trials were at low risk of bias.',
     '把 82 项随机试验、10332 名肠易激患者按菌株拆开，GRADE 确定性几乎处处塌到低或极低。82 项试验中只有 24 项属低偏倚风险。'),
    ('Raw CFU counts are close to meaningless divorced from strain. The infant colic strain works at 100 million CFU/d, which is 100 to 1,000 times LOWER than the counts marketed on adult tubs.',
     '脱离菌株，单看 CFU 数字几近毫无意义。婴儿肠绞痛那个菌株在 1 亿 CFU/天下有效，比成人罐装上标的数字低 100 至 1000 倍。'),
    ('The same contraindications apply as for any live organism: central venous catheter, neutropenia, severe immunocompromise, critical illness, preterm infants.',
     '与任何活菌一样的禁忌同样适用：中心静脉置管、中性粒细胞减少、重度免疫抑制、危重症、早产儿。'),
  ],
  refs='Goodoory & Ford PMID 37541528; NCCIH; Cochrane CD006095.pub5 PMID 40931979'),

I(SKIP, 'D', 'B. infantis 35624 (single strain)', 'B. infantis 35624（单一菌株）',
  '1 billion CFU/d, one capsule, assessed at 4 weeks. This is the trialled dose, not a dose shown to work.',
  '10 亿 CFU/天，每日一粒，4 周后评估。这是试验用的剂量，不是被证明有效的剂量。',
  'On current evidence, no clearly identifiable group.', '按现有证据，没有可清楚界定的适用人群。',
  pros=[
    ('Composite probiotic products containing B. infantis showed small effects on abdominal pain (SMD 0.22) and bloating (SMD 0.30). Those effects belong to the composite, not to this strain.',
     '含 B. infantis 的复方益生菌产品对腹痛（SMD 0.22）和腹胀（SMD 0.30）有小幅效应。那些效应属于复方，不属于这个菌株。'),
  ],
  cons=[
    ('This is the clearest case of the strain-specificity argument cutting AGAINST the industry. It is the product that taught consumers to look for a strain number, and the dedicated meta-analysis of 5 studies found the SINGLE strain had no effect on abdominal pain, bloating or bowel habit satisfaction.',
     '这是“菌株特异性”这个论点反过来对行业不利的最清楚案例。正是这个产品教会消费者去看菌株编号，而一项针对 5 项研究的专门 meta 分析发现，单一菌株对腹痛、腹胀和排便满意度都没有效应。'),
    ('The whole reputation rests on one 2006 trial plus an anti-inflammatory mechanism story about the IL-10 to IL-12 ratio.',
     '它的全部声誉建立在 2006 年的一项试验，加上一个关于 IL-10 与 IL-12 比值的抗炎机制叙事之上。'),
    ('The AGA recommends against probiotics for irritable bowel syndrome outside clinical trials, which is this product primary market.',
     '美国胃肠病学会建议在临床试验之外不要用益生菌治疗肠易激，而那正是这个产品的主要市场。'),
    ('Bifidobacterium species specifically have caused whole-genome-sequencing-confirmed bacteraemia in preterm infants.',
     '双歧杆菌属确实在早产儿中造成过经全基因组测序确认的菌血症。'),
  ],
  refs='Yuan PMID 28166427; Goodoory & Ford PMID 37541528; AGA PMID 32531291'),

I(SKIP, 'C', 'Krill oil', '磷虾油',
  '2 g/d for 24 weeks in the knee osteoarthritis trial. Bioavailability trials used about 1.1 g/d of actual omega-3.',
  '膝骨关节炎试验为 2 克/天、持续 24 周。生物利用度试验用的是实际 omega-3 约 1.1 克/天。',
  'At most, people wanting a given rise in omega-3 index from a smaller dose. That is a biomarker advantage.',
  '最多适用于希望用更小剂量把 omega-3 指数提上去的人。那是生物标志物层面的优势。',
  pros=[
    ('The absorption argument has support. A 72-person trial at matched 1.1 g/d found krill oil produced about 1.5-fold higher increments in plasma EPA and DHA than fish oil.',
     '吸收方面的论点有支持。一项 72 人的试验在同为 1.1 克/天的条件下发现，磷虾油使血浆 EPA 和 DHA 的升幅比鱼油高约 1.5 倍。'),
    ('Contains astaxanthin, which is why it does not oxidise as readily as bulk fish oil.',
     '含虾青素，这也是它不像散装鱼油那样容易氧化的原因。'),
  ],
  cons=[
    ('The joint claim collapsed under proper testing. The largest randomised trial (JAMA, n=262 with knee osteoarthritis and effusion-synovitis, 2 g/d for 24 weeks) found mean pain change -19.9 with krill oil versus -20.2 with placebo. A trial-sequential-analysis review across 5 trials and 700 patients found no significant improvement in knee pain, stiffness or lipid profile.',
     '关节方面的说法在正规检验下崩塌。规模最大的随机试验（JAMA，262 名膝骨关节炎伴积液滑膜炎患者，2 克/天服 24 周）显示磷虾油组疼痛平均变化 -19.9，安慰剂组 -20.2。一项含试验序贯分析、涵盖 5 项试验 700 名患者的综述发现，膝痛、僵硬和血脂均无显著改善。'),
    ('It is priced as a premium product on the strength of a biomarker advantage, and delivers far less EPA and DHA per capsule than a concentrate.',
     '它凭一个生物标志物优势按高端产品定价，而每粒提供的 EPA 和 DHA 远少于浓缩型产品。'),
    ('Crustacean and shellfish allergy is a genuine and under-warned contraindication.',
     '甲壳类和贝类过敏是真实存在却警示不足的禁忌。'),
    ('Same anticoagulant, antiplatelet and atrial fibrillation cautions as any omega-3 source once dose rises.',
     '一旦剂量上升，与任何 omega-3 来源一样，需注意抗凝、抗血小板和房颤方面的问题。'),
  ],
  refs='Laslett JAMA 2024 PMID 38776073; Pimentel PMID 39126570; Loukil PMID 42144109'),

I(SKIP, 'D', 'Cod liver oil', '鱼肝油',
  'No established effective dose for any endpoint. The binding constraint is retinol, not omega-3.',
  '对任何终点都没有确立的有效剂量。真正的限制因素是视黄醇，不是 omega-3。',
  'Arguably nobody, given modern alternatives.', '考虑到现代替代品，可以说没有适用人群。',
  pros=[
    ('Historically it was an effective vitamin D and vitamin A vehicle in populations with little sun and poor diets, and that history is real.',
     '在缺少日照、饮食贫乏的人群中，它历史上确实是有效的维生素 D 和维生素 A 载体，这段历史是真实的。'),
    ('Natural triglyceride oils absorb well.',
     '天然甘油三酯型油脂吸收良好。'),
  ],
  cons=[
    ('You cannot increase the omega-3 dose without simultaneously increasing preformed vitamin A, which has a real toxicity ceiling of 3,000 µg/d and is teratogenic. That is a dose-limiting design flaw, not a feature.',
     '你无法在不同时增加预成型维生素 A 的情况下提高 omega-3 剂量，而前者有 3000 微克/天的真实毒性上限，并且致畸。这是限制剂量的设计缺陷，不是特色。'),
    ('As an omega-3 source it is dilute, so reaching a therapeutic dose requires a large volume of oil and therefore a large retinol load.',
     '作为 omega-3 来源它很稀，要达到治疗剂量需要很大体积的油，也就意味着很大的视黄醇负荷。'),
    ('Standard obstetric advice in several countries is to avoid liver and liver-oil supplements in pregnancy.',
     '若干国家的标准产科建议是妊娠期避免肝脏和肝油类补充剂。'),
    ('Typically sold as a bulk, often flavoured liquid, which is the format that performed worst in oxidation surveys. Fermented cod liver oil has no quality advantage.',
     '通常以散装、常带调味的液体形式出售，而这正是在氧化调查中表现最差的形式。“发酵鱼肝油”没有质量优势。'),
  ],
  refs='Dyerberg PMID 20638827; Jackowski PMID 26688721; Heller PMID 30626234'),

I(SKIP, 'C', 'ALA from flaxseed, chia or walnut oil', '亚麻籽、奇亚籽或核桃油中的 ALA',
  'Adequate intake 1.6 g/d for men and 1.1 g/d for women. No upper limit; the practical constraint is calories from oil.',
  '适宜摄入量：男性 1.6 克/天，女性 1.1 克/天。没有上限；实际限制是油带来的热量。',
  'People who eat no marine products at all and will not take algal oil. It at least maintains essential fatty acid status.',
  '完全不吃海产、也不愿吃藻油的人。它至少能维持必需脂肪酸的状态。',
  pros=[
    ('It is a genuinely essential fatty acid, so adequate intake matters.',
     '它确实是必需脂肪酸，所以摄入足量是有意义的。'),
    ('The Cochrane review found a signal for arrhythmia reduction, RR 0.73 (0.55-0.97) at moderate certainty. Note that rests on just 2 trials, 4,912 participants and 173 events.',
     'Cochrane 综述发现心律失常减少的信号，RR 0.73（0.55-0.97），确定性中等。注意这只建立在 2 项试验、4912 名受试者和 173 个事件之上。'),
  ],
  cons=[
    ('The plant-based omega-3, same benefits claim is the core deception. Conversion of ALA to EPA is a few percent and to DHA is well under one percent in adults, and it is further suppressed by high dietary linoleic acid. A flaxseed capsule does not deliver what a fish oil or algal oil capsule delivers.',
     '“植物来源的 omega-3，同样的好处”是核心误导。成人体内 ALA 转化为 EPA 只有百分之几，转化为 DHA 远低于百分之一，而且会被膳食中较高的亚油酸进一步压制。一粒亚麻籽胶囊提供不了鱼油或藻油胶囊提供的东西。'),
    ('Cochrane found increased ALA probably makes little or no difference to all-cause mortality, RR 1.01 (0.84-1.20).',
     'Cochrane 发现增加 ALA 对全因死亡可能几乎没有影响，RR 1.01（0.84-1.20）。'),
    ('Anyone relying on it to achieve DHA status is making a mistake, and that includes pregnant women and vegans wanting fetal DHA supply. Algal DHA is the correct product there.',
     '任何指望靠它达到 DHA 水平的人都做错了，这包括希望为胎儿提供 DHA 的孕妇和纯素者。那种情况下正确的产品是藻油 DHA。'),
    ('Note the arrhythmia finding for ALA points the opposite way to the atrial fibrillation excess seen with marine omega-3 (HR 1.25), so the two should not be treated as interchangeable in either direction.',
     '注意 ALA 的心律失常结果与海洋 omega-3 观察到的房颤增多（HR 1.25）方向相反，因此两者在任何方向上都不应被当作可以互换。'),
  ],
  refs='Cochrane PMID 32114706; Gencer PMID 34612056; NASEM DRI'),

I(SKIP, 'C', 'Algal oil (vegan DHA and EPA)', '藻油（纯素 DHA 与 EPA）',
  'Matched to fish oil equivalents. For pregnancy the tested DHA doses are the same as fish-derived, 200-1,000 mg/d.',
  '按鱼油等效量给药。妊娠期已验证的 DHA 剂量与鱼源相同，为 200 至 1000 毫克/天。',
  'Vegans and vegetarians, people avoiding fish contaminants, and people with fish or shellfish allergy.',
  '纯素者与素食者、想避开鱼类污染物的人、以及鱼类或贝类过敏者。',
  pros=[
    ('It is the correct product for vegans, who cannot obtain preformed EPA and DHA any other way, and for whom ALA conversion is inadequate.',
     '对纯素者而言这是正确的产品，他们无法通过其他途径获得预成型的 EPA 和 DHA，而 ALA 转化又不足。'),
    ('Statistically non-inferior to fish oil for plasma phospholipid DHA and EPA in a 74-person trial over 6 to 14 weeks.',
     '在一项 74 人、持续 6 至 14 周的试验中，血浆磷脂 DHA 和 EPA 在统计学上不劣于鱼油。'),
    ('Avoids methylmercury, dioxins and PCBs, which is a legitimate reason to choose it in pregnancy.',
     '可避开甲基汞、二噁英和多氯联苯，这是妊娠期选择它的正当理由。'),
  ],
  cons=[
    ('There is no clinical outcome trial of algal oil for any endpoint. The only evidence is a 74-person biomarker study, and the credibility it borrows comes from the fish oil outcome trials, which were largely null.',
     '藻油在任何终点上都没有临床结局试验。唯一的证据是一项 74 人的生物标志物研究，而它借来的可信度出自鱼油的结局试验，那些试验大体上是阴性的。'),
    ('Non-inferiority on a biomarker is not superiority, and marketing implying algal DHA is cleaner therefore better conflates contaminant avoidance with efficacy.',
     '在生物标志物上不劣于并不等于优于，而暗示“藻油 DHA 更干净所以更好”的营销，把避开污染物和有效性混为一谈。'),
    ('Cost per milligram of DHA is usually higher than fish oil.',
     '每毫克 DHA 的成本通常高于鱼油。'),
    ('Products are DHA-dominant, and DHA raises LDL more than EPA does (+6.9% versus +2.2% in a head-to-head crossover), which matters if LDL is your limiting problem.',
     '这类产品以 DHA 为主，而 DHA 升高低密度脂蛋白的幅度大于 EPA（头对头交叉试验中为 +6.9% 对 +2.2%），如果低密度脂蛋白是你的主要问题，这一点很要紧。'),
  ],
  refs='Bailey PMID 41096614; Cochrane PMID 32114706; Allaire ComparED PMID 27281302'),

I(SKIP, 'D', 'Wheat bran and insoluble fibre supplements for IBS', '麦麸与不溶性纤维补充剂用于肠易激',
  '10 g/d was the comparator dose in the head-to-head primary care trial. No effective dose exists for IBS.',
  '在基层医疗的头对头试验中，对照剂量为 10 克/天。对肠易激不存在有效剂量。',
  'Nobody with irritable bowel syndrome.', '没有任何肠易激综合征患者适用。',
  pros=[
    ('As a food it contributes to total dietary fibre intake, and total fibre intake is associated with 15 to 30% reductions in all-cause and cardiovascular mortality.',
     '作为食物它计入总膳食纤维摄入，而总纤维摄入与全因和心血管死亡降低 15 至 30% 相关。'),
  ],
  cons=[
    ('It is the clearest case in this document of a refuted product still sold into the exact indication where it failed. Pooled bran trials: relative risk of persistent IBS symptoms 0.90 (0.79-1.03), null. Soluble fibre by contrast gave 0.83 (0.73-0.94), NNT 7.',
     '这是本文中最清楚的一个例子：一个已被推翻的产品，仍然被卖进它恰恰失败的那个适应证。合并的麦麸试验：肠易激症状持续的相对风险 0.90（0.79-1.03），阴性。相比之下可溶性纤维为 0.83（0.73-0.94），NNT 7。'),
    ('In the three-arm primary care trial, bran at 10 g/d for 12 weeks did not beat placebo on symptom severity at 3 months (-58 versus -49 points, P=0.61) while psyllium did (-90 points, P=0.03). Bran also had the lowest completion rate of the three arms at 56%.',
     '在三臂基层医疗试验中，麦麸 10 克/天服 12 周，在 3 个月时的症状严重度上未超过安慰剂（-58 对 -49 分，P=0.61），而洋车前子做到了（-90 分，P=0.03）。麦麸组的完成率也是三组中最低的，为 56%。'),
    ('Bran is the fibre most consistently reported to WORSEN abdominal pain and distension.',
     '麦麸是最常被报告会加重腹痛和腹胀的纤维。'),
    ('Contraindicated with strictures, adhesions or a history of obstruction, and unsuitable in coeliac disease and non-coeliac gluten sensitivity.',
     '肠狭窄、粘连或有梗阻史者禁用，乳糜泻和非乳糜泻性麸质敏感者不适用。'),
  ],
  refs='Moayyedi PMID 25070054; Bijkerk BMJ 2009 PMID 19713235; Nagarajan PMID 26148247'),

I(SKIP, 'D', 'Over-the-counter digestive enzyme blends', '非处方复合消化酶',
  'No evidence-derived dose exists. Products are dosed in non-comparable proprietary activity units by design.',
  '不存在源自证据的剂量。这类产品按互不可比的专有活性单位计量，且这是设计如此。',
  'No identified group. Use a matched single enzyme for a diagnosed deficiency instead.',
  '没有确定的适用人群。确诊缺乏某种酶时，应使用对应的单一酶。',
  pros=[
    ('One 120-participant double-blind placebo-controlled trial of a fungal multi-enzyme blend reported improvement in functional dyspepsia symptom and quality-of-life scores. Single centre, proprietary product, symptom-scale endpoints.',
     '一项 120 人的双盲安慰剂对照试验，用真菌来源的复合酶，报告功能性消化不良症状和生活质量评分改善。单中心、专有产品、症状量表终点。'),
  ],
  cons=[
    ('The category is built on a fabricated disease. There is no recognised syndrome of generalised digestive enzyme insufficiency in healthy adults, and clinically meaningful malabsorption does not appear until roughly 90% of exocrine pancreatic function is lost.',
     '这个品类建立在一个被制造出来的疾病之上。健康成人不存在公认的“全面消化酶不足”综合征，而要出现有临床意义的吸收不良，需要外分泌胰腺功能损失约 90%。'),
    ('It borrows credibility from prescription pancreatic enzyme replacement, which treats a real, objectively diagnosable condition.',
     '它从处方胰酶替代治疗那里借来了可信度，而后者治疗的是一种真实、可客观诊断的疾病。'),
    ('The main harm is diagnostic delay. Self-treating undiagnosed persistent gut symptoms delays diagnosis of coeliac disease, inflammatory bowel disease, pancreatic disease and colorectal cancer.',
     '主要危害是延误诊断。自行处理未确诊的持续胃肠症状，会延误乳糜泻、炎症性肠病、胰腺疾病和结直肠癌的诊断。'),
    ('A properly controlled trial in autism (43 children, double-blind crossover) found no clinically significant improvement, in a population where these products were heavily promoted.',
     '一项在孤独症人群中设计规范的试验（43 名儿童，双盲交叉）未发现有临床意义的改善，而这些产品曾在该人群中被大力推销。'),
  ],
  refs='Ullah PMID 37976892; Munasinghe PMID 20204691; de la Iglesia-Garcia PMID 27941156'),

I(SKIP, 'C', 'L-glutamine for gut repair', 'L-谷氨酰胺用于修复肠道',
  '15 g/d as 5 g three times daily for 8 weeks in the only supportive gut trial.',
  '唯一一项支持性肠道试验为 15 克/天，即 5 克每日三次、持续 8 周。',
  'Narrowly, post-infectious diarrhoea-predominant IBS with objectively documented increased intestinal permeability.',
  '严格来说，仅限感染后腹泻型肠易激且已客观证实肠道通透性增加者。',
  pros=[
    ('The one supportive trial is genuinely striking: 106 patients, 79.6% versus 5.8% achieved a 50-point reduction in IBS severity score over 8 weeks, with normalisation of intestinal permeability.',
     '唯一那项支持性试验的结果确实惊人：106 名患者，8 周内肠易激严重度评分下降 50 分的比例为 79.6% 对 5.8%，且肠道通透性恢复正常。'),
    ('It has a licensed pharmaceutical use in sickle cell disease, where a phase 3 trial reduced median pain crises from 4.0 to 3.0.',
     '它在镰状细胞病中有获批的药用，一项三期试验把疼痛危机中位数从 4.0 降到 3.0。'),
  ],
  cons=[
    ('A 14-fold difference in response rate is an effect size almost never seen in functional gastrointestinal disease, and the 5.8% placebo response is far below the 30 to 40% typical of IBS trials. That combination demands scepticism, not enthusiasm. It is a single-centre, unreplicated result.',
     '应答率相差 14 倍，这种效应量在功能性胃肠病中几乎从未出现，而 5.8% 的安慰剂应答率远低于肠易激试验典型的 30 至 40%。这两点合在一起要求的是怀疑，不是兴奋。它是一项单中心、未被重复的结果。'),
    ('There is a mortality signal in the critically ill. In the REDOXS trial, high-dose glutamine given to 1,223 critically ill adults with multi-organ failure raised 28-day mortality to 32.4% versus 27.2%, adjusted OR 1.28.',
     '在危重患者中存在死亡信号。REDOXS 试验中，对 1223 名多器官功能衰竭的危重成人给予高剂量谷氨酰胺，28 天死亡率升至 32.4%，对照为 27.2%，校正 OR 1.28。'),
    ('Contraindicated in hepatic impairment, cirrhosis and any history of hepatic encephalopathy, because glutamine is metabolised to glutamate and ammonia.',
     '肝功能不全、肝硬化和有肝性脑病史者禁用，因为谷氨酰胺会代谢为谷氨酸和氨。'),
    ('It is the chemical anchor of the entire leaky gut supplement economy, and the gap between that market and the evidence is enormous.',
     '它是整个“肠漏”补充剂经济的化学支点，而那个市场与证据之间的差距极大。'),
  ],
  refs='Zhou Gut 2019 PMID 30108163; REDOXS PMID 23594003; Niihara NEJM PMID 30021096'),

I(SKIP, 'C', 'Prebiotics: inulin, FOS, GOS', '益生元：菊粉、FOS、GOS',
  '5-15 g/d of inulin-type fructans, clustering around 10-12 g/d in constipation trials. Tolerance is the binding constraint above 10-15 g/d.',
  '菊粉型果聚糖 5 至 15 克/天，便秘试验多集中在 10 至 12 克/天。超过 10 至 15 克/天后，限制因素是耐受性。',
  'Adults with chronic constipation and habitually low fibre intake who tolerate fermentation.',
  '慢性便秘、平时纤维摄入偏低、且能耐受发酵的成人。',
  pros=[
    ('Inulin does something measurable for constipation: stool frequency SMD 0.69 and Bristol stool consistency SMD 1.07 across 5 trials and 252 subjects.',
     '菊粉对便秘确有可测量的作用：5 项试验、252 名受试者中，排便频率 SMD 0.69，Bristol 大便性状 SMD 1.07。'),
    ('It reliably increases faecal bifidobacteria, and it is cheap.',
     '它能稳定增加粪便中的双歧杆菌，而且便宜。'),
    ('EFSA has an authorised claim for native chicory inulin at 12 g/d for maintenance of normal defecation, which is more regulatory support than most items here have.',
     'EFSA 批准了天然菊苣菊粉在 12 克/天下“维持正常排便”的健康声称，这比本文多数条目获得的监管支持都多。'),
  ],
  cons=[
    ('Feed your good bacteria is the current premium reframing of what used to be sold as roughage, at roughly ten times the price per gram of fibre.',
     '“喂养你的好细菌”是把过去当作粗纤维卖的东西重新包装成高端品，而每克纤维的价格约为过去的十倍。'),
    ('The endpoint switch is the specific dishonesty: marketing leans on the reliable rise in faecal bifidobacteria, which is a microbiological measurement, and lets the consumer infer a clinical benefit.',
     '具体的不诚实之处在于偷换终点：营销依赖的是粪便双歧杆菌可靠上升这个微生物学指标，却让消费者自行推断出临床获益。'),
    ('The inulin meta-analysis states explicitly that pain and bloating do NOT improve. The largest systematic review of prebiotics in IBS found the data sparse and insufficient to establish efficacy.',
     '菊粉的 meta 分析明确写道，疼痛和腹胀并未改善。关于益生元治疗肠易激的最大系统综述认为数据稀少，不足以确立有效性。'),
    ('Self-defeating for IBS patients on or considering a low-FODMAP diet, because inulin, FOS and GOS ARE the fermentable oligosaccharides that diet removes. Anyone whose dominant symptom is bloating or flatulence should not take these.',
     '对正在或考虑低 FODMAP 饮食的肠易激患者来说，这么做是自相矛盾的，因为菊粉、FOS 和 GOS 正是那种饮食要去掉的可发酵低聚糖。任何以腹胀或排气为主要症状的人都不应服用。'),
  ],
  refs='Ford PMID 30294792; Collado Yurrita PMID 25208775; Reynolds Lancet 2019 PMID 30638909'),

I(SKIP, 'C', 'Saffron, SAMe and other mood botanicals', '藏红花、SAMe 及其他情绪类植物制剂',
  'Saffron 30 mg/d of standardised extract. SAMe 1,600-3,200 mg/d as an adjunct.',
  '藏红花：标准化提取物 30 毫克/天。SAMe：1600 至 3200 毫克/天作为辅助用药。',
  'At most, adults with mild to moderate depression taking no serotonergic medication, and only with a clinician involved.',
  '最多适用于轻中度抑郁、未服用任何 5-羟色胺能药物的成人，且必须有临床医生参与。',
  pros=[
    ('Saffron: 21 randomised trials found Beck Depression Inventory -4.86 (-6.58 to -3.14) and Beck Anxiety Inventory -5.29.',
     '藏红花：21 项随机试验显示 Beck 抑郁量表 -4.86（-6.58 至 -3.14），Beck 焦虑量表 -5.29。'),
    ('SAMe: one 2024 meta-analysis of 23 trials and 2,183 participants found monotherapy better than placebo, SMD -0.58 (-0.93 to -0.23), at moderate certainty.',
     'SAMe：2024 年一项纳入 23 项试验、2183 名受试者的 meta 分析发现单药优于安慰剂，SMD -0.58（-0.93 至 -0.23），确定性中等。'),
  ],
  cons=[
    ('Saffron effect sizes are implausibly large for the trial size. One meta-analysis reported SMD -1.22 versus placebo, which is better than licensed antidepressants achieve. Effect sizes that large in small short trials usually indicate small-study effects and a narrow research base, so treat it as a red flag rather than a selling point.',
     '藏红花的效应量相对试验规模大得不合常理。一项 meta 分析报告相对安慰剂 SMD 为 -1.22，好过获批抗抑郁药能达到的水平。小样本短周期试验出现这么大的效应量，通常说明存在小研究效应和研究基础狭窄，因此应视为警示信号而非卖点。'),
    ('Self-report instruments move while clinician-rated instruments do not, which is the classic pattern of an unblinded expectancy effect.',
     '自评量表在动，而临床医生评定的量表不动，这正是未盲化预期效应的典型形态。'),
    ('SAMe has directly conflicting meta-analyses published in the same year. A second 2024 analysis of 14 trials and 1,522 participants found NO significant difference versus placebo, versus imipramine or versus escitalopram. Report both.',
     'SAMe 在同一年有两篇结论直接冲突的 meta 分析。2024 年另一项涵盖 14 项试验、1522 名受试者的分析发现，相对安慰剂、丙咪嗪和艾司西酞普兰均无显著差异。两篇都要报告。'),
    ('SAMe is associated with switching into mania or hypomania in bipolar disorder, and homocysteine can rise on it. Both saffron and SAMe carry serotonin syndrome risk with serotonergic medication. Saffron should be avoided in pregnancy on the basis of traditional emmenagogue use.',
     'SAMe 在双相障碍中与转为躁狂或轻躁狂有关，服用期间同型半胱氨酸可能升高。藏红花和 SAMe 与 5-羟色胺能药物合用都有 5-羟色胺综合征风险。基于传统上的通经用途，藏红花在妊娠期应当避免。'),
    ('Depression is a condition where delaying effective treatment carries real risk. Neither of these should displace a clinical assessment.',
     '抑郁是一种延误有效治疗会带来真实风险的疾病。这两样都不应取代临床评估。'),
  ],
  refs='Yang PMID 29849461; Ghaderi PMID 31987241; Limveeraprajak PMID 38423354; Peng PMID 38199136'),

I(SKIP, 'C', 'Quercetin and taurine', '槲皮素与牛磺酸',
  'Quercetin at least 500 mg/d for the blood pressure effect. Taurine 0.5-6 g/d.',
  '槲皮素：要产生降压效应需至少 500 毫克/天。牛磺酸：0.5 至 6 克/天。',
  'At most, people with elevated blood pressure or components of metabolic syndrome, for a small surrogate effect.',
  '最多适用于血压偏高或有代谢综合征组分的人，且只是一个小的替代终点效应。',
  pros=[
    ('Taurine has the strongest human surrogate data of any longevity compound here: 25 trials, 1,024 participants, systolic -4.0 mmHg (-7.29 to -0.71), diastolic -1.51 mmHg, fasting glucose -5.9 mg/dL, all dose-dependent.',
     '在本文所有抗衰老类化合物中，牛磺酸的人体替代终点数据最强：25 项试验、1024 名受试者，收缩压 -4.0 mmHg（-7.29 至 -0.71），舒张压 -1.51 mmHg，空腹血糖 -5.9 mg/dL，均呈剂量依赖。'),
    ('Quercetin at 500 mg/d or more gave systolic -4.45 mmHg and diastolic -2.98 mmHg in the dose-stratified analysis.',
     '在按剂量分层的分析中，槲皮素 500 毫克/天及以上使收缩压降低 4.45 mmHg，舒张压降低 2.98 mmHg。'),
  ],
  cons=[
    ('The taurine longevity story was directly refuted in humans in 2025. The 2023 Science paper showed taurine declines with age in mice, monkeys and humans and extends lifespan in mice. A 2025 Aging Cell paper found circulating taurine is NOT associated with age, muscle mass, strength, physical performance or mitochondrial function in humans.',
     '牛磺酸与长寿的故事在 2025 年已被人体研究直接推翻。2023 年《科学》那篇论文显示牛磺酸在小鼠、猴和人体内随年龄下降，并延长小鼠寿命。2025 年《Aging Cell》一篇论文发现，在人体中循环牛磺酸与年龄、肌肉质量、力量、体能表现或线粒体功能都无关联。'),
    ('Quercetin effect sizes are shrinking as the evidence matures. The 2016 meta-analysis gave systolic -3.04 mmHg; the 2023 umbrella review of meta-analyses found only -1.9 mmHg with heterogeneity of 88%, and nothing else significant, at very low certainty.',
     '随着证据成熟，槲皮素的效应量在缩小。2016 年的 meta 分析给出收缩压 -3.04 mmHg；2023 年针对 meta 分析的伞式综述只得到 -1.9 mmHg，异质性 88%，其余指标均不显著，确定性极低。'),
    ('A 2 to 4 mmHg systolic reduction is small next to any antihypertensive drug or to sodium reduction.',
     '收缩压降低 2 至 4 mmHg，相比任何降压药或减少钠摄入都很小。'),
    ('Quercetin inhibits CYP3A4 and P-glycoprotein, so treat it as an interaction risk with ciclosporin, tacrolimus, CYP3A4-metabolised statins, warfarin and many chemotherapeutics. It is also a topoisomerase inhibitor in vitro, which is a specific reason not to combine it with chemotherapy.',
     '槲皮素抑制 CYP3A4 和 P-糖蛋白，因此与环孢素、他克莫司、经 CYP3A4 代谢的他汀、华法林以及许多化疗药合用都应视为相互作用风险。它在体外还是拓扑异构酶抑制剂，这是不要与化疗联用的具体理由。'),
    ('Taurine effects are additive with antihypertensives, insulin and sulfonylureas.',
     '牛磺酸的效应与降压药、胰岛素和磺脲类叠加。'),
  ],
  refs='Tzang PMID 38755142; Singh Science 2023; Marcangeli Aging Cell 2025 PMC12507425; Serban PMID 27405810; Arabi PMID 37654199'),

# ============================================================ AVOID
I(AVOID, 'A', 'Beta-carotene supplements', 'β-胡萝卜素补充剂',
  'No effective dose exists. The doses tested and found harmful were 20 mg/d and 30 mg/d combined with retinyl palmitate.',
  '不存在有效剂量。经检验并被发现有害的剂量是 20 毫克/天，以及 30 毫克/天与棕榈酸视黄酯联用。',
  'Essentially nobody at supplemental doses. Narrow exceptions: clinical vitamin A deficiency and erythropoietic protoporphyria.',
  '在补充剂剂量下基本没有适用人群。狭窄的例外：临床维生素 A 缺乏症和红细胞生成性原卟啉病。',
  pros=[
    ('Dietary carotenoids from vegetables are not implicated in any of the harm below. Eating carrots is fine.',
     '来自蔬菜的膳食类胡萝卜素与下面所有危害都无关。吃胡萝卜没问题。'),
  ],
  cons=[
    ('ATBC (n=29,133 male smokers, Finland, 5-8 years): 20 mg/d increased lung cancer incidence by 18% (95% CI 3 to 36%) and total mortality by 8% (1 to 16%).',
     'ATBC（29133 名男性吸烟者，芬兰，5 至 8 年）：20 毫克/天使肺癌发病率增加 18%（95% CI 3 至 36%），总死亡增加 8%（1 至 16%）。'),
    ('CARET (n=18,314 smokers, former smokers and asbestos-exposed workers): lung cancer RR 1.28 (1.04-1.57), all-cause death RR 1.17 (1.03-1.33), lung cancer death RR 1.46 (1.07-2.00). Stopped early.',
     'CARET（18314 名吸烟者、曾吸烟者和石棉接触工人）：肺癌 RR 1.28（1.04-1.57），全因死亡 RR 1.17（1.03-1.33），肺癌死亡 RR 1.46（1.07-2.00）。提前终止。'),
    ('Cochrane, 78 randomised trials and 296,707 participants: beta-carotene increased mortality, RR 1.05 (1.01-1.09).',
     'Cochrane 纳入 78 项随机试验、296707 名受试者：β-胡萝卜素增加死亡，RR 1.05（1.01-1.09）。'),
    ('This is the canonical case where the industry own logic failed in public. The observational data were strong, the mechanism was plausible, the trials were large and well conducted, and the answer was that the pill killed people.',
     '这是行业自身逻辑在公开场合失效的经典案例。观察性数据很强，机制看起来合理，试验规模大、执行规范，而答案是这药片让人死得更多。'),
    ('Absolute avoidance in current smokers, former smokers and anyone with asbestos exposure. USPSTF grade D recommendation.',
     '现吸烟者、曾吸烟者和任何有石棉接触史者绝对避免。USPSTF 为 D 级推荐。'),
  ],
  refs='ATBC PMID 8127329; CARET PMID 8602180; Cochrane Bjelakovic PMID 22419320; USPSTF PMID 35727271'),

I(AVOID, 'A', 'Vitamin E at or above 400 IU/d', '维生素 E 400 IU/天及以上',
  'No effective preventive dose exists. 400 IU/d was the harmful dose. ATBC low-dose 50 mg/d produced neither benefit nor lung cancer harm.',
  '不存在有效的预防剂量。400 IU/天是有害剂量。ATBC 中 50 毫克/天的低剂量既无获益也未增加肺癌。',
  'Documented deficiency, which in practice means fat malabsorption: abetalipoproteinaemia, cholestatic liver disease, cystic fibrosis, short bowel.',
  '已证实的缺乏，实际上指脂肪吸收不良：无β脂蛋白血症、胆汁淤积性肝病、囊性纤维化、短肠。',
  pros=[
    ('Ataxia with vitamin E deficiency requires high-dose replacement, and that is a genuine indication.',
     '维生素 E 缺乏性共济失调需要大剂量替代治疗，这是一个真实的适应证。'),
    ('There is a narrow niche in biopsy-proven non-diabetic non-alcoholic steatohepatitis, where 800 IU/d improved histology in the PIVENS trial. That is a hepatology decision, not a self-care one.',
     '在活检证实的非糖尿病性非酒精性脂肪性肝炎中有一个狭窄的适用面，PIVENS 试验中 800 IU/天改善了组织学表现。那是肝病科的决定，不是自我保健。'),
  ],
  cons=[
    ('A dose-response meta-analysis of 19 trials and 135,967 participants found high-dose trials produced 39 additional deaths per 10,000 persons (95% CI 3 to 74, P=0.035). Low-dose trials showed -16 per 10,000.',
     '一项纳入 19 项试验、135967 名受试者的剂量效应 meta 分析发现，高剂量试验每 1 万人多出 39 例死亡（95% CI 3 至 74，P=0.035）。低剂量试验为每万人 -16 例。'),
    ('SELECT (n=34,887 men): 400 IU/d of synthetic all-rac-alpha-tocopheryl acetate raised prostate cancer incidence by 17%, HR 1.17 (99% CI 1.004-1.36, P=0.008). The excess emerged in extended follow-up after supplementation had already stopped.',
     'SELECT（34887 名男性）：400 IU/天的合成全消旋α-生育酚醋酸酯使前列腺癌发病率升高 17%，HR 1.17（99% CI 1.004-1.36，P=0.008）。这个超出部分是在补充已经停止后的延长随访中出现的。'),
    ('Haemorrhagic stroke RR 1.22 (1.00-1.48) across 9 trials and 118,765 participants, which is one additional haemorrhagic stroke per 1,250 people treated.',
     '9 项试验、118765 名受试者中出血性卒中 RR 1.22（1.00-1.48），相当于每治疗 1250 人多出 1 例出血性卒中。'),
    ('Contraindicated with warfarin, direct oral anticoagulants, aspirin, clopidogrel and other antiplatelets, because impaired coagulation is the endpoint EFSA used to set its limit.',
     '与华法林、直接口服抗凝药、阿司匹林、氯吡格雷及其他抗血小板药禁用，因为 EFSA 设定上限所依据的终点正是凝血功能受损。'),
    ('USPSTF grade D. Note the limits diverge sharply: 1,000 mg/d supplemental alpha-tocopherol in the US, but 300 mg/d from ALL sources in the EU.',
     'USPSTF 为 D 级。注意上限差异悬殊：美国为补充剂α-生育酚 1000 毫克/天，而欧盟为全部来源合计 300 毫克/天。'),
  ],
  refs='SELECT Klein PMID 21990298; Miller PMID 15537682; Schurks BMJ PMID 21051774; USPSTF PMID 35727271; EFSA J 2024 PMID 39099617'),

I(AVOID, 'A', 'Selenium at 200 µg/d', '硒 200 微克/天',
  'RDA is 55 µg/d and food intake meets it in most Western diets. 200 µg/d is the dose used in the failed and harmful trials.',
  '推荐摄入量为 55 微克/天，多数西方饮食通过食物即可满足。200 微克/天是那些失败并有害的试验所用剂量。',
  'People with genuinely low selenium status: low-soil regions, long-term parenteral nutrition, severe malabsorption.',
  '硒状态确实偏低的人：土壤低硒地区、长期肠外营养、严重吸收不良。',
  pros=[
    ('It prevents Keshan disease, a selenium-deficiency cardiomyopathy, in genuinely deficient populations. That is a real and important indication.',
     '在确实缺硒的人群中，它能预防克山病，一种缺硒性心肌病。这是一个真实且重要的适应证。'),
    ('There is a Grade B signal for mild Graves orbitopathy in selenium-suboptimal European populations at 200 µg/d for 6 months, resting on a single 159-patient trial.',
     '在硒偏低的欧洲人群中，200 微克/天服 6 个月对轻度 Graves 眼病有一个 B 级信号，依据是一项 159 名患者的单一试验。'),
  ],
  cons=[
    ('Cochrane, 10 randomised trials and 27,232 participants: any cancer RR 1.01 (0.93-1.10) from the low-risk-of-bias studies. That is HIGH-certainty evidence of NO benefit. The cancer-prevention reputation rests on a secondary endpoint of a 1996 skin cancer trial that was not designed to test it.',
     'Cochrane 纳入 10 项随机试验、27232 名受试者：在低偏倚风险研究中，任何癌症 RR 1.01（0.93-1.10）。这是高确定性地证明无获益。它的防癌名声建立在 1996 年一项皮肤癌试验的次要终点上，而那项试验并非为此设计。'),
    ('SELECT (n=35,533 men, 200 µg/d L-selenomethionine) found prostate cancer HR 1.09 (99% CI 0.93-1.27). No preventive effect, and the trial stopped early for futility.',
     'SELECT（35533 名男性，200 微克/天 L-硒代甲硫氨酸）显示前列腺癌 HR 1.09（99% CI 0.93-1.27）。没有预防作用，试验因无效提前终止。'),
    ('Incident type 2 diabetes hazard ratio 1.55 (1.03-2.33) over a mean 7.7 years at 200 µg/d, with excess risk concentrated in those already in the highest tertile of baseline plasma selenium. This harm appears at HALF the US upper limit.',
     '在 200 微克/天下，平均 7.7 年内新发 2 型糖尿病风险比为 1.55（1.03-2.33），超额风险集中在基线血浆硒本已处于最高三分位的人身上。这个危害出现在美国上限的一半剂量处。'),
    ('The therapeutic window is narrow. EFSA lowered its upper limit to 255 µg/d in 2023 with alopecia as the critical endpoint, and derived its lowest-observed-adverse-effect level of 330 µg/d from the SELECT trial itself.',
     '治疗窗很窄。EFSA 于 2023 年把上限下调至 255 微克/天，关键终点为脱发，其 330 微克/天的最低可观察不良作用水平正是取自 SELECT 试验本身。'),
    ('Stacking is how people get there: a 200 µg tablet on top of a multivitamin containing 55-70 µg plus dietary intake.',
     '人们正是通过叠加达到这个剂量的：一片 200 微克的硒，加上含 55 至 70 微克的复合维生素，再加饮食摄入。'),
  ],
  refs='Cochrane Vinceti PMID 29376219; SELECT PMID 19066370 and PMID 21990298; Stranges PMID 17620655; EFSA 2023'),

I(AVOID, 'D', 'Preformed vitamin A at or above 10,000 IU', '预成型维生素 A 10000 IU 及以上',
  'RDA 900 µg RAE for men and 700 µg for women. The upper limit is 3,000 µg/d, which is exactly 10,000 IU.',
  '推荐摄入量：男性 900 微克 RAE，女性 700 微克。上限为 3000 微克/天，正好等于 10000 IU。',
  'Clinical vitamin A deficiency in low-income settings, fat malabsorption, cystic fibrosis. In replete Western adults, nobody.',
  '低收入地区的临床维生素 A 缺乏、脂肪吸收不良、囊性纤维化。在营养充足的西方成人中，没有适用人群。',
  pros=[
    ('WHO supplementation saves lives in vitamin-A-deficient children, particularly in measles. That is one of the highest-value public health interventions in existence, and it is not what an over-the-counter 10,000 IU capsule is for.',
     '在维生素 A 缺乏的儿童中，尤其是麻疹患儿，WHO 的补充方案能挽救生命。那是现存价值最高的公共卫生干预之一，但这不是一粒非处方 10000 IU 胶囊的用途。'),
  ],
  cons=[
    ('CARET showed net harm: 25,000 IU/d of retinyl palmitate plus 30 mg beta-carotene gave all-cause death RR 1.17 (1.03-1.33) and lung cancer death RR 1.46 (1.07-2.00).',
     'CARET 显示净危害：25000 IU/天棕榈酸视黄酯加 30 毫克β-胡萝卜素，全因死亡 RR 1.17（1.03-1.33），肺癌死亡 RR 1.46（1.07-2.00）。'),
    ('Over-the-counter products at 10,000 IU/d sit exactly AT the upper limit, leaving zero headroom for diet, liver consumption or a second supplement.',
     '10000 IU/天的非处方产品正好卡在上限，饮食、吃动物肝脏或第二种补充剂都没有余量。'),
    ('It is teratogenic. Preformed vitamin A above the upper limit in pregnancy is a hard contraindication, and prenatal products should use beta-carotene rather than retinol.',
     '它有致畸性。妊娠期预成型维生素 A 超过上限属硬性禁忌，孕期产品应使用β-胡萝卜素而非视黄醇。'),
    ('Unlike beta-carotene, preformed vitamin A is not subject to feedback regulation on absorption, so chronic excess accumulates and causes hepatotoxicity, intracranial hypertension and bone loss.',
     '与β-胡萝卜素不同，预成型维生素 A 的吸收不受反馈调节，因此长期过量会蓄积，导致肝毒性、颅内压升高和骨质流失。'),
    ('Contraindicated in liver disease of any kind, since retinol is stored in and toxic to the liver.',
     '任何类型的肝病禁用，因为视黄醇储存于肝脏并对肝脏有毒。'),
  ],
  refs='CARET PMID 8602180; Cochrane PMID 22419320; IOM DRI NBK56068'),

I(AVOID, 'B', 'High-dose vitamin B6', '大剂量维生素 B6',
  'RDA is 1.3 mg/d. EFSA set the upper limit at 12 mg/d in 2023. The US IOM figure is still 100 mg/d.',
  '推荐摄入量为 1.3 毫克/天。EFSA 于 2023 年把上限定为 12 毫克/天。美国 IOM 的数字仍是 100 毫克/天。',
  'People on isoniazid, cycloserine, hydralazine or penicillamine, where B6 is protective against drug-induced neuropathy. Pregnant women with nausea and vomiting, at obstetric direction.',
  '服用异烟肼、环丝氨酸、肼屈嗪或青霉胺者，此时 B6 可预防药物性神经病。妊娠恶心呕吐的孕妇，需遵产科医嘱。',
  pros=[
    ('It genuinely prevents isoniazid-induced peripheral neuropathy at 10-50 mg/d, which is a real and important indication.',
     '在 10 至 50 毫克/天下，它确实能预防异烟肼引起的周围神经病，这是一个真实而重要的适应证。'),
    ('Pyridoxine with doxylamine is a first-line option for nausea and vomiting of pregnancy, ahead of antiemetics.',
     '吡哆醇与多西拉敏联用是妊娠恶心呕吐的一线选择，优先于止吐药。'),
  ],
  cons=[
    ('This is the clearest case in this document where the product category actively causes the harm it claims to prevent. Nerve support, neuropathy and PMS formulas routinely deliver 50-100 mg of B6 to people with no deficiency, which is four to eight times the current European upper limit.',
     '这是本文中最清楚的一个例子：一个产品品类主动造成了它声称要预防的那种伤害。“神经营养”“神经病变”和经前综合征类配方常规给到 50 至 100 毫克 B6，而使用者并不缺乏，这是当前欧洲上限的 4 至 8 倍。'),
    ('Sensory peripheral neuropathy is the dose- and duration-dependent toxicity: numbness, burning, ataxia and loss of proprioception. EFSA set its 12 mg/d limit on exactly this, from a reference point of 50 mg/d in case reports.',
     '感觉性周围神经病是剂量和时长依赖的毒性表现：麻木、烧灼感、共济失调、位置觉丧失。EFSA 正是据此把上限定为 12 毫克/天，参考点取自个案报告中的 50 毫克/天。'),
    ('Choosing pyridoxal-5-phosphate (P5P) at a premium does NOT prevent it. The toxicity is not form-specific.',
     '花高价选择磷酸吡哆醛（P5P）并不能避免这一点。毒性与形式无关。'),
    ('Audit your total intake. Anyone on a B-complex, a fortified energy drink and a nerve or stress formula can easily stack past 100 mg without noticing.',
     '要核算总摄入量。同时在吃复合 B 族、喝强化能量饮料、又吃“神经”或“抗压”配方的人，很容易不知不觉叠加超过 100 毫克。'),
    ('An observational safety signal exists: in men, a 10-year average intake above 20 mg/d from individual supplements gave lung cancer HR 1.82 (1.25-2.65). Confounding by smoking is possible, but the direction is not reassuring.',
     '存在一个观察性安全信号：在男性中，通过单一补充剂十年平均摄入超过 20 毫克/天，肺癌 HR 为 1.82（1.25-2.65）。可能受吸烟混杂影响，但这个方向并不令人安心。'),
  ],
  refs='EFSA PMID 37207271; Cochrane Matthews PMID 26348534; Brasky JCO PMID 28829668'),

I(AVOID, 'B', 'Green tea extract (EGCG)', '绿茶提取物（EGCG）',
  'Commercial products commonly deliver 250-500 mg EGCG/d. EFSA found significant transaminase elevation at or above 800 mg/d.',
  '市售产品常提供 EGCG 250 至 500 毫克/天。EFSA 发现在 800 毫克/天及以上转氨酶显著升高。',
  'Nobody for the marketed indications. Drinking green tea is fine and is a different exposure.',
  '就其宣传的功效而言没有适用人群。喝绿茶没问题，那是完全不同的暴露方式。',
  pros=[
    ('Green tea as a beverage has no meaningful hepatotoxicity signal and is a perfectly reasonable drink.',
     '绿茶作为饮品没有有意义的肝毒性信号，是一种完全合理的饮料。'),
  ],
  cons=[
    ('EFSA was unable to identify ANY dose of EGCG from green tea extracts that can be considered safe, because catechin composition varies with cultivar, growing conditions and extraction method. That is an unusual regulatory conclusion.',
     'EFSA 无法确定绿茶提取物中任何一个可被认定为安全的 EGCG 剂量，因为儿茶素组成随品种、种植条件和提取工艺而变化。这是一个不寻常的监管结论。'),
    ('NIH LiverTox documents more than 100 published cases of clinically apparent liver injury: median latency 42 days, 95% hepatocellular, severe in 35%, and transplantation in 8%, with fatal acute liver failure reported.',
     'NIH 的 LiverTox 收录了 100 例以上有明确临床表现的肝损伤：中位潜伏期 42 天，95% 为肝细胞型，35% 为重度，8% 接受肝移植，并有致死性急性肝衰竭的报告。'),
    ('HLA-B*35:01 was present in 72% of green tea liver-injury cases versus 11-15% of controls, and essentially nobody is tested for it.',
     '在绿茶相关肝损伤病例中，72% 携带 HLA-B*35:01，对照组为 11 至 15%，而基本上没有人会去做这个检测。'),
    ('The weight-loss claim, which is why most of it is sold, has clinically trivial effect sizes where measurable.',
     '减重这个卖点是它主要的销售理由，但在可测量的范围内，其效应量在临床上微不足道。'),
    ('It was the second most used of six hepatotoxic botanicals in US national survey data. Avoid entirely with pre-existing liver disease, raised transaminases, or another hepatotoxic agent such as methotrexate, isoniazid, high-dose paracetamol or alcohol.',
     '在美国全国调查数据中，它是六种肝毒性植物里使用第二多的。已有肝病、转氨酶升高，或正在使用甲氨蝶呤、异烟肼、大剂量对乙酰氨基酚或酒精等其他肝毒性物质者，应完全避免。'),
  ],
  refs='EFSA J 2018;16(4):5239; NIH LiverTox NBK547925; Likhitsup PMID 39102266'),

I(AVOID, 'C', 'Ashwagandha (Withania somnifera)', '南非醉茄（印度人参）',
  '300-600 mg/d of root extract standardised to about 5% withanolides. Liver injury occurred at ordinary retail doses.',
  '标准化至约 5% 醉茄内酯的根提取物 300 至 600 毫克/天。肝损伤发生在普通零售剂量下。',
  'No population with a demonstrated clinical need. Anyone with liver disease should be steered away entirely.',
  '没有任何人群有已证实的临床需要。有肝病者应完全避开。',
  pros=[
    ('There is a real but small and fragile efficacy signal: pooled Perceived Stress Scale -4.72 (-8.45 to -0.99), Hamilton Anxiety Scale -2.19 (-3.83 to -0.55) and serum cortisol -2.58 across 9 randomised trials and 558 patients.',
     '存在一个真实但微弱且脆弱的有效性信号：9 项随机试验、558 名患者中，感知压力量表 -4.72（-8.45 至 -0.99），Hamilton 焦虑量表 -2.19（-3.83 至 -0.55），血清皮质醇 -2.58。'),
    ('A sleep meta-analysis of 5 trials and 400 participants found SMD -0.59, with larger effects at 600 mg/d or more over 8 weeks or longer.',
     '一项涵盖 5 项试验、400 名受试者的睡眠 meta 分析得出 SMD -0.59，在 600 毫克/天以上、8 周以上时效应更大。'),
  ],
  cons=[
    ('Hepatotoxicity is documented in a prospective case series from Iceland and the US DILIN network: jaundice with nausea, lethargy and pruritus after a latency of 2 to 12 weeks, cholestatic or mixed injury, symptoms lasting 5 to 20 weeks.',
     '肝毒性已被冰岛和美国 DILIN 网络的前瞻性病例系列记录：潜伏 2 至 12 周后出现黄疸伴恶心、乏力和瘙痒，损伤为胆汁淤积型或混合型，症状持续 5 至 20 周。'),
    ('In an Indian case series, 5 of 23 patients had pre-existing chronic liver disease, 3 developed acute-on-chronic liver failure and ALL 3 DIED. Pre-existing liver disease is the hard contraindication.',
     '在一组印度病例中，23 名患者里有 5 人本已有慢性肝病，3 人发展为慢加急性肝衰竭，3 人全部死亡。已有肝病是硬性禁忌。'),
    ('Denmark banned it in food supplements in 2023 after its national food institute concluded no safe intake level could be established.',
     '丹麦国家食品研究所认定无法确定安全摄入水平后，丹麦于 2023 年禁止其用于食品补充剂。'),
    ('It raises T4 and can precipitate thyrotoxicosis or require a levothyroxine dose reduction. Published cases exist.',
     '它会升高 T4，可能诱发甲状腺毒症，或需要下调左甲状腺素剂量。已有公开病例。'),
    ('Avoid in pregnancy (traditional abortifacient use), in autoimmune disease and in transplant recipients (immunostimulant effects), and with sedatives (additive).',
     '妊娠期（传统上有堕胎用途）、自身免疫性疾病和移植受者（免疫刺激作用）应避免，与镇静剂合用有叠加作用。'),
    ('The trials are small, short, mostly single-centre and frequently manufacturer-sponsored, with subjective questionnaire endpoints and no hard endpoint anywhere in the literature.',
     '这些试验规模小、周期短、多为单中心，且常由厂商资助，终点是主观问卷，整个文献中没有任何硬终点。'),
  ],
  refs='Bjornsson Liver Int PMID 31991029; Arumugam PMID 39348746; Cheah PMID 34559859; DTU Denmark 2020'),

I(AVOID, 'D', 'Weight-loss, fat-burner and energy blends', '减重、燃脂与能量复方',
  'Garcinia products commonly supply 500-1,500 mg of extract. No effective dose has been demonstrated for clinically meaningful weight loss.',
  '藤黄类产品常提供 500 至 1500 毫克提取物。对有临床意义的减重，没有任何剂量被证明有效。',
  'No identifiable group. This is the worst-behaving corner of the entire supplement market.',
  '没有可界定的适用人群。这是整个补充剂市场表现最恶劣的角落。',
  pros=[
    ('None identified. The efficacy literature does not support clinically meaningful weight loss from these products.',
     '没有发现任何优点。有效性文献不支持这些产品能带来有临床意义的减重。'),
  ],
  cons=[
    ('Weight-loss and energy products account for 71.8% (67.6-76.1) of the supplement-related emergency department visits presenting with cardiac symptoms, out of an estimated 23,005 visits per year in the US.',
     '在美国每年约 23005 次补充剂相关急诊中，出现心脏症状的病例有 71.8%（67.6-76.1）来自减重和能量类产品。'),
    ('Adults aged 20-34 accounted for 28.0% of all such visits, so the demographic bearing the harm is young and otherwise healthy.',
     '20 至 34 岁成人占全部此类就诊的 28.0%，也就是说承担危害的是年轻、本来健康的群体。'),
    ('The FDA acted against Hydroxycut in 2009 after hepatotoxicity reports including a death. NIH LiverTox maintains a dedicated monograph for Garcinia cambogia acute liver injury including fulminant hepatic failure.',
     '2009 年，FDA 在收到包括一例死亡在内的肝毒性报告后对 Hydroxycut 采取行动。NIH LiverTox 为藤黄属的急性肝损伤（包括暴发性肝衰竭）专门设有专论。'),
    ('These are proprietary blends, and 40.9% of all adulterated supplements in the FDA database are weight-loss products. Undeclared sibutramine, withdrawn from all major markets in 2010, and prohibited stimulants such as DMAA, deterenol, octodrine, oxilofrine and phenpromethamine are repeatedly found.',
     '它们是专有配方，而 FDA 掺假产品数据库中 40.9% 是减重产品。未标示的西布曲明（2010 年已从所有主要市场撤市）以及 DMAA、deterenol、octodrine、oxilofrine、phenpromethamine 等违禁兴奋剂被反复检出。'),
    ('Serotonin syndrome has been reported with garcinia in combination with SSRIs, SNRIs and MAOIs. Contraindicated in liver disease, arrhythmia and hypertension.',
     '藤黄与 SSRI、SNRI 和 MAOI 合用已有 5-羟色胺综合征报告。肝病、心律失常和高血压者禁用。'),
  ],
  refs='Geller NEJM PMID 26465986; Tucker PMID 30646238; LiverTox NBK548087; Cohen Clin Toxicol 2021'),

I(AVOID, 'D', 'Bodybuilding and test-booster products', '健美与睾酮提升类产品',
  'Not applicable. Dosing is label-driven and the label does not reflect the contents.',
  '不适用。剂量由标签决定，而标签并不反映实际成分。',
  'Nobody. Any muscle gain is attributable to undeclared controlled substances the user did not consent to take.',
  '没有适用人群。任何增肌都归因于使用者未曾同意服用的、未标示的受管制物质。',
  pros=[
    ('None. There is no hype-versus-reality gap to argue about, because the products contain drugs they do not declare.',
     '没有优点。这里不存在“宣传与现实”的落差可争论，因为产品里就含有它们没有申报的药物。'),
  ],
  cons=[
    ('The DILIN prospective series enrolled 44 men, mean age 33, median latency 73 days of use. 100% were jaundiced, 84% had pruritus, 71% required hospitalisation, and liver biopsy in 59% showed mild hepatitis with profound cholestasis.',
     'DILIN 前瞻性病例系列纳入 44 名男性，平均 33 岁，中位使用潜伏期 73 天。100% 出现黄疸，84% 有瘙痒，71% 需住院，59% 做了肝活检的患者显示轻度肝炎伴重度胆汁淤积。'),
    ('Chemical analysis of the implicated products repeatedly finds anabolic androgenic steroids not declared on the label. These are controlled substances.',
     '对涉事产品的化学分析反复检出标签上未申报的合成代谢雄激素类固醇。这些属于受管制物质。'),
    ('Of 44 products sold as SARMs, only 23 (52%) contained any SARM, 17 (39%) contained a different unapproved drug, 4 (9%) contained no active compound at all, and only 18 (41%) had accurate labels.',
     '在 44 款以 SARM 名义销售的产品中，只有 23 款（52%）含有任何一种 SARM，17 款（39%）含有另一种未获批药物，4 款（9%）完全不含活性成分，只有 18 款（41%）标签准确。'),
    ('Muscle building accounted for 11.9% of adulterated products in the FDA database, and bodybuilding products caused 45 of 130 herbal and dietary supplement liver injury cases in the DILIN cohort.',
     '在 FDA 掺假产品数据库中，增肌类占 11.9%；在 DILIN 队列中，130 例草药与膳食补充剂肝损伤病例中有 45 例由健美产品引起。'),
    ('ABCB11 gene variants were over-represented in cases versus ethnically matched controls, so some individuals are genetically far more vulnerable and have no way to know.',
     '与族裔匹配的对照相比，病例中 ABCB11 基因变异更常见，因此某些人在遗传上更易受害，而他们无从得知。'),
  ],
  refs='Stolz PMID 30934130; Navarro DILIN PMID 25043597; Van Wagoner JAMA PMID 29183075; Geller PMID 26465986'),

I(AVOID, 'A', 'Sexual-enhancement products', '性功能增强类产品',
  'Not applicable. Undeclared pharmaceutical doses are present at pharmacological levels.',
  '不适用。其中含有达到药理水平的、未标示的药物剂量。',
  'Nobody, from any retailer, at any price.', '没有适用人群。不论在哪买、卖多少钱。',
  pros=[
    ('None. The only defensible use of this evidence is categorical avoidance.',
     '没有优点。这些证据唯一站得住的用途就是整类回避。'),
  ],
  cons=[
    ('Sexual enhancement is the single largest adulterated category: 353 of 776 products (45.5%) in the FDA tainted-products database, from 146 different companies.',
     '性功能增强是掺假最多的单一品类：在 FDA 掺假产品数据库的 776 个产品中占 353 个（45.5%），来自 146 家不同公司。'),
    ('The adulterants are PDE5 inhibitors, chiefly sildenafil and structural analogues designed to evade detection. Undeclared sildenafil taken by someone on nitrates for angina is a route to catastrophic hypotension in a patient who does not know they took a PDE5 inhibitor.',
     '掺假物是 PDE5 抑制剂，主要是西地那非及为规避检测而设计的结构类似物。一个正在服用硝酸酯类抗心绞痛药的人吃下未标示的西地那非，会走向灾难性低血压，而他并不知道自己吃了 PDE5 抑制剂。'),
    ('Enforcement does not work on this category. Of 27 FDA-recalled supplements still purchasable and re-analysed a mean 34.3 months after recall, 18 (66.7%) still contained banned drugs and 63% contained the same adulterant the FDA had already ordered removed.',
     '监管执法在这个品类上不起作用。在召回后平均 34.3 个月仍能买到并被重新检测的 27 款 FDA 召回产品中，18 款（66.7%）仍含违禁药，63% 含有 FDA 早已要求移除的同一种掺假物。'),
    ('Tucker found 157 products (20.2%) contained more than one unapproved ingredient, and on resampling 19 of 28 repeatedly flagged products (67.9%) had merely switched to a different adulterant.',
     'Tucker 发现 157 个产品（20.2%）含有一种以上未获批成分，而重新取样时，28 个被反复标记的产品中有 19 个（67.9%）只是换成了另一种掺假物。'),
  ],
  refs='Tucker PMID 30646238; Cohen JAMA 2014; FDA CDER tainted products database'),

I(AVOID, 'D', 'High-dose folic acid plus B12 for cardiovascular prevention', '以心血管预防为目的的大剂量叶酸加 B12',
  'The Norwegian trials used folic acid 0.8 mg/d plus B12 0.4 mg/d, with or without B6 40 mg/d.',
  '挪威试验用的是叶酸 0.8 毫克/天加 B12 0.4 毫克/天，有的另加 B6 40 毫克/天。',
  'Nobody for cardiovascular prevention. Periconceptional folic acid at 400 µg is a completely different indication and should not be conflated with this.',
  '以心血管预防为目的没有适用人群。围孕期 400 微克叶酸是完全不同的适应证，不应与此混为一谈。',
  pros=[
    ('B vitamins do reliably lower homocysteine, which was the mechanistic rationale. The mechanism worked. The clinical benefit did not follow.',
     'B 族维生素确实能稳定降低同型半胱氨酸，这曾是其机制依据。机制成立了，临床获益没有随之而来。'),
  ],
  cons=[
    ('The homocysteine hypothesis is dead as a cardiovascular target. HOPE-2 (n=5,522, 5 years) lowered homocysteine with no effect on major vascular events (RR 0.95, 0.84-1.07). SEARCH (n=12,064, 6.7 years) cut it 28% with RR 1.04 (0.97-1.12) for major vascular events.',
     '同型半胱氨酸作为心血管靶点已经死了。HOPE-2（n=5522，5 年）降低了同型半胱氨酸，对主要血管事件无效应（RR 0.95，0.84-1.07）。SEARCH（n=12064，6.7 年）使其下降 28%，主要血管事件 RR 为 1.04（0.97-1.12）。'),
    ('There is a positive cancer harm signal. Pooled Norwegian trials in 6,837 patients with ischaemic heart disease: cancer incidence HR 1.21 (1.03-1.41), cancer mortality HR 1.38 (1.07-1.79), and all-cause mortality also raised.',
     '存在明确的癌症危害信号。挪威两项试验在 6837 名缺血性心脏病患者中的合并分析：癌症发病 HR 1.21（1.03-1.41），癌症死亡 HR 1.38（1.07-1.79），全因死亡同样升高。'),
    ('Anyone with a history of cancer or at elevated cancer risk should not take high-dose folic acid for cardiovascular indications.',
     '有癌症史或癌症风险升高者，不应为心血管目的服用大剂量叶酸。'),
    ('Vitamin B12 use before and during chemotherapy was associated with worse disease-free survival (HR 1.83, 1.15-2.92) and worse overall survival (HR 2.04, 1.22-3.40) in a prospective study nested in a phase 3 trial.',
     '在一项嵌套于三期试验的前瞻性研究中，化疗前及化疗期间使用维生素 B12 与更差的无病生存（HR 1.83，1.15-2.92）和总生存（HR 2.04，1.22-3.40）相关。'),
    ('The upper limit for synthetic folic acid is 1,000 µg/d, and it was set to prevent masking of B12 deficiency neuropathy.',
     '合成叶酸上限为 1000 微克/天，设定这个上限的目的是防止掩盖 B12 缺乏性神经病。'),
  ],
  refs='Ebbing JAMA 2009 PMID 19920236; HOPE-2; SEARCH; Ambrosone JCO PMID 31855498; USPSTF PMID 35727271'),

I(AVOID, 'D', 'Antioxidants during chemotherapy', '化疗期间的抗氧化剂',
  'Not applicable. No dose is recommended and the concern is temporal rather than numeric.',
  '不适用。不推荐任何剂量，问题在于时间点而非数字。',
  'Nobody. Documented deficiency should be corrected under oncology supervision, with timing discussed against the chemotherapy schedule.',
  '没有适用人群。已证实的缺乏应在肿瘤科监督下纠正，并就时间安排与化疗周期一并讨论。',
  pros=[
    ('A plain reference-intake-level multivitamin showed no adverse association in the same dataset, so ordinary nutritional support is not the concern here.',
     '在同一数据集中，普通参考摄入量水平的复合维生素未显示不良关联，因此普通营养支持不是这里担心的对象。'),
  ],
  cons=[
    ('The theoretical objection is direct and mechanistic: several cytotoxic classes including anthracyclines, platinum agents and alkylating agents work partly through oxidative damage, and radiotherapy works through free radical generation. Supplementing antioxidants may blunt the treatment.',
     '理论上的反对意见直接且机制明确：包括蒽环类、铂类和烷化剂在内的多类细胞毒药物部分通过氧化损伤起效，放疗则通过产生自由基起效。补充抗氧化剂可能削弱治疗。'),
    ('SWOG S0221 (n=1,134 women with high-risk early breast cancer on cyclophosphamide, doxorubicin and paclitaxel): any antioxidant (vitamins A, C, E, carotenoids, CoQ10) taken both before and during chemotherapy gave recurrence adjusted HR 1.41 (0.98-2.04, P=0.06).',
     'SWOG S0221（1134 名接受环磷酰胺、多柔比星和紫杉醇治疗的高危早期乳腺癌女性）：化疗前及化疗期间服用任何抗氧化剂（维生素 A、C、E、类胡萝卜素、辅酶 Q10），复发的校正 HR 为 1.41（0.98-2.04，P=0.06）。'),
    ('In the same study, vitamin B12 taken before and during chemotherapy gave disease-free survival HR 1.83 (1.15-2.92) and overall survival HR 2.04 (1.22-3.40). Iron was also associated with worse outcomes.',
     '同一研究中，化疗前及化疗期间服用维生素 B12，无病生存 HR 为 1.83（1.15-2.92），总生存 HR 为 2.04（1.22-3.40）。铁也与更差的结局相关。'),
    ('SELECT establishes in a randomised setting that high-dose antioxidant supplementation can INCREASE cancer incidence: vitamin E 400 IU/d raised prostate cancer HR 1.17 in 34,887 men.',
     'SELECT 在随机试验的框架下确立了大剂量抗氧化剂补充可以增加癌症发病：在 34887 名男性中，400 IU/天维生素 E 使前列腺癌 HR 升至 1.17。'),
    ('Honest caveat: SWOG S0221 is observational within a randomised trial, and the headline antioxidant hazard ratio crossed 1 with P=0.06. Nobody should overstate it. But cancer patients are the most aggressively targeted and least protected supplement consumers, and support your body through chemo is sold with no evidence and a plausible mechanism of harm.',
     '诚实的限定：SWOG S0221 是随机试验内部的观察性分析，其抗氧化剂主要风险比跨过了 1，P=0.06。谁都不该夸大它。但肿瘤患者是被最猛烈针对、又最缺保护的补充剂消费者，而“化疗期间给身体加把力”这个卖点，既没有证据，又有一个说得通的致害机制。'),
  ],
  refs='Ambrosone SWOG S0221 JCO PMID 31855498; SELECT PMID 21990298; Cochrane PMID 22419320'),

I(AVOID, 'B', 'Probiotics in critical illness', '危重症患者使用益生菌',
  'Not applicable. The relevant ceiling is a population restriction rather than a milligram figure.',
  '不适用。真正的限制是人群禁忌，而不是一个毫克数字。',
  'Nobody in critical illness. See the strain-specific entry for the two indications where probiotics do work.',
  '危重症患者没有适用人群。益生菌确实有效的那两个适应证见菌株特异性条目。',
  pros=[
    ('None in this population. In non-critically-ill patients there are two narrow indications with real evidence, covered separately.',
     '在这个人群中没有优点。在非危重患者中有两个有真实证据的狭窄适应证，另有条目说明。'),
  ],
  cons=[
    ('PROPATRIA is the most important negative trial in this entire field. In 296 patients with predicted severe acute pancreatitis given a multispecies synbiotic enterally twice daily for 28 days: mortality 24 of 152 (16%) versus 9 of 144 (6%), RR 2.53 (1.22-5.25). Infectious complications were not reduced (RR 1.06).',
     'PROPATRIA 是整个领域最重要的阴性试验。296 名预测为重症急性胰腺炎的患者，经肠道每日两次给予多菌种合生元共 28 天：死亡 152 人中 24 例（16%），对照 144 人中 9 例（6%），RR 2.53（1.22-5.25）。感染性并发症并未减少（RR 1.06）。'),
    ('Nine cases of bowel ischaemia occurred, eight of them fatal, versus zero on placebo. The plausible mechanism is that fermentable substrate plus bacteria in a gut with compromised splanchnic perfusion increases local oxygen demand.',
     '发生了 9 例肠缺血，其中 8 例死亡，安慰剂组为零。一个说得通的机制是：在内脏灌注受损的肠道里，可发酵底物加上细菌会增加局部氧需求。'),
    ('The FDA warned providers after a preterm infant died of probiotic-associated Bifidobacterium sepsis, and cases of severe or fatal infection in premature infants receiving probiotics are documented.',
     '在一名早产儿死于益生菌相关双歧杆菌脓毒症后，FDA 向医疗机构发出警示，且早产儿接受益生菌后发生重症或致死性感染的病例已有记录。'),
    ('Saccharomyces boulardii fungaemia is documented in ICU patients with central venous catheters, which is the dominant risk factor.',
     '在带中心静脉导管的 ICU 患者中已有布拉氏酵母菌血症的记录，而中心静脉导管正是主要危险因素。'),
    ('Absolute contraindications: predicted severe acute pancreatitis, multi-organ failure, central venous catheter, neutropenia, severe immunocompromise, and preterm infants outside a supervised NICU protocol.',
     '绝对禁忌：预测为重症急性胰腺炎、多器官功能衰竭、中心静脉置管、中性粒细胞减少、重度免疫抑制，以及未在新生儿重症监护监督方案内的早产儿。'),
  ],
  refs='PROPATRIA Besselink Lancet PMID 18279948; NCCIH; case report PMID 41476631'),

I(AVOID, 'B', 'Calcium supplements on top of an adequate diet', '饮食已足够时再补钙',
  'The trials used at least 500 mg/d elemental calcium. Adult reference intake is 1,000-1,200 mg/d TOTAL from all sources.',
  '试验用的是元素钙至少 500 毫克/天。成人参考摄入量是全部来源合计 1000 至 1200 毫克/天。',
  'People with genuinely low dietary calcium, below about 600-700 mg/d, particularly institutionalised elderly, and patients on long-term glucocorticoids.',
  '膳食钙确实偏低（低于约 600 至 700 毫克/天）的人，尤其是养老机构中的老人，以及长期使用糖皮质激素的患者。',
  pros=[
    ('With vitamin D in frail, calcium-and-D-deplete institutionalised elderly, it cuts hip fracture: RR 0.84 (0.74-0.96) across 9 trials and 49,853 people. That population is real and the effect is real.',
     '在体弱、钙与维生素 D 双缺的养老机构老人中，与维生素 D 合用可降低髋部骨折：9 项试验、49853 人中 RR 0.84（0.74-0.96）。那个人群是真实的，效应也是真实的。'),
    ('Correcting a genuine dietary shortfall is sensible, and food sources are preferable where possible.',
     '纠正真实的膳食缺口是合理的，能通过食物解决就优先用食物。'),
  ],
  cons=[
    ('It does very little for fractures in ordinary community-dwelling adults. WHI, the largest trial ever run (n=36,282 postmenopausal women, 1,000 mg calcium plus 400 IU vitamin D, 7 years) gained 1.06% hip bone density but produced hip fracture HR 0.88 (0.72-1.08) and spine 0.90 (0.74-1.10). Both null.',
     '在普通社区居住的成人中，它对骨折作用很小。有史以来规模最大的 WHI 试验（36282 名绝经后女性，1000 毫克钙加 400 IU 维生素 D，7 年）髋部骨密度提高 1.06%，但髋部骨折 HR 为 0.88（0.72-1.08），脊柱为 0.90（0.74-1.10）。两者均为阴性。'),
    ('There is a cardiovascular harm signal. Bolland pooled 15 placebo-controlled trials of calcium at least 500 mg/d without vitamin D: patient-level myocardial infarction HR 1.31 (1.02-1.67, P=0.035) across 5 studies and 8,151 participants. A separate WHI reanalysis plus updated meta-analysis gave myocardial infarction RR 1.24 (1.07-1.45, P=0.004).',
     '存在心血管危害信号。Bolland 合并了 15 项不含维生素 D、钙剂量至少 500 毫克/天的安慰剂对照试验：5 项研究、8151 名受试者的个体数据显示心肌梗死 HR 1.31（1.02-1.67，P=0.035）。另一项 WHI 再分析加更新 meta 分析给出心肌梗死 RR 1.24（1.07-1.45，P=0.004）。'),
    ('Kidney stones increased significantly in WHI, HR 1.17 (1.02-1.34). This is the clearest confirmed harm in that trial.',
     'WHI 中肾结石显著增加，HR 1.17（1.02-1.34）。这是该试验中最明确被确认的危害。'),
    ('Supplementing on top of adequate dietary intake gets you the possible cardiovascular downside and no bone upside. Supplement the shortfall only.',
     '在饮食已足够的基础上再补，得到的是可能的心血管坏处，而没有骨骼上的好处。只补缺口。'),
    ('Absorption falls above about 500 mg per dose, so split doses. Chelates levothyroxine, bisphosphonates, tetracyclines and fluoroquinolones. Avoid in hypercalcaemia, primary hyperparathyroidism, sarcoidosis and a history of calcium-containing stones.',
     '单次超过约 500 毫克后吸收率下降，所以要分次服。会与左甲状腺素、双膦酸盐、四环素类和氟喹诺酮类螯合。高钙血症、原发性甲状旁腺功能亢进、结节病和含钙结石史者应避免。'),
  ],
  refs='WHI Jackson NEJM PMID 16481635; Bolland BMJ 2010 PMID 20671013; Bolland BMJ 2011 PMID 21505219; Cochrane PMID 24729336'),

]
